// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.datatypes.hardware_info;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class HardwareAddressT {
  private long addr;

  public long getAddr() { return addr; }

  public void setAddr(long addr) { this.addr = addr; }


  public HardwareAddressT() {
    this.addr = 0L;
  }
}

