// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.datatypes.hardware_info;

@SuppressWarnings("unused")
public final class McuType {
  private McuType() { }
  public static final int Other = 0;
  public static final int ESP8266 = 1;
  public static final int ESP32 = 2;

  public static final String[] names = { "Other", "ESP8266", "ESP32", };

  public static String name(int e) { return names[e]; }
}

