// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ChangeVRMSettingsRequest implements flatbuffers.IUnpackableObject<ChangeVRMSettingsRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChangeVRMSettingsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChangeVRMSettingsRequest(bb:flatbuffers.ByteBuffer, obj?:ChangeVRMSettingsRequest):ChangeVRMSettingsRequest {
  return (obj || new ChangeVRMSettingsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChangeVRMSettingsRequest(bb:flatbuffers.ByteBuffer, obj?:ChangeVRMSettingsRequest):ChangeVRMSettingsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChangeVRMSettingsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

vrmJson():string|null
vrmJson(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
vrmJson(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startChangeVRMSettingsRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addVrmJson(builder:flatbuffers.Builder, vrmJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, vrmJsonOffset, 0);
}

static endChangeVRMSettingsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChangeVRMSettingsRequest(builder:flatbuffers.Builder, vrmJsonOffset:flatbuffers.Offset):flatbuffers.Offset {
  ChangeVRMSettingsRequest.startChangeVRMSettingsRequest(builder);
  ChangeVRMSettingsRequest.addVrmJson(builder, vrmJsonOffset);
  return ChangeVRMSettingsRequest.endChangeVRMSettingsRequest(builder);
}

unpack(): ChangeVRMSettingsRequestT {
  return new ChangeVRMSettingsRequestT(
    this.vrmJson()
  );
}


unpackTo(_o: ChangeVRMSettingsRequestT): void {
  _o.vrmJson = this.vrmJson();
}
}

export class ChangeVRMSettingsRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public vrmJson: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const vrmJson = (this.vrmJson !== null ? builder.createString(this.vrmJson!) : 0);

  return ChangeVRMSettingsRequest.createChangeVRMSettingsRequest(builder,
    vrmJson
  );
}
}
