// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class CompleteStayAlignedResponse implements flatbuffers.IUnpackableObject<CompleteStayAlignedResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CompleteStayAlignedResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCompleteStayAlignedResponse(bb:flatbuffers.ByteBuffer, obj?:CompleteStayAlignedResponse):CompleteStayAlignedResponse {
  return (obj || new CompleteStayAlignedResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCompleteStayAlignedResponse(bb:flatbuffers.ByteBuffer, obj?:CompleteStayAlignedResponse):CompleteStayAlignedResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CompleteStayAlignedResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startCompleteStayAlignedResponse(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endCompleteStayAlignedResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCompleteStayAlignedResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  CompleteStayAlignedResponse.startCompleteStayAlignedResponse(builder);
  return CompleteStayAlignedResponse.endCompleteStayAlignedResponse(builder);
}

unpack(): CompleteStayAlignedResponseT {
  return new CompleteStayAlignedResponseT();
}


unpackTo(_o: CompleteStayAlignedResponseT): void {}
}

export class CompleteStayAlignedResponseT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return CompleteStayAlignedResponse.createCompleteStayAlignedResponse(builder);
}
}
