// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { CustomOSCTrackerMapping, CustomOSCTrackerMappingT } from '../../solarxr-protocol/rpc/custom-osctracker-mapping.js';


export class CustomOSCProfile implements flatbuffers.IUnpackableObject<CustomOSCProfileT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CustomOSCProfile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCustomOSCProfile(bb:flatbuffers.ByteBuffer, obj?:CustomOSCProfile):CustomOSCProfile {
  return (obj || new CustomOSCProfile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCustomOSCProfile(bb:flatbuffers.ByteBuffer, obj?:CustomOSCProfile):CustomOSCProfile {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CustomOSCProfile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

enabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

address():string|null
address(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
address(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

port():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

trackers(index: number, obj?:CustomOSCTrackerMapping):CustomOSCTrackerMapping|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new CustomOSCTrackerMapping()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

trackersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCustomOSCProfile(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addEnabled(builder:flatbuffers.Builder, enabled:boolean) {
  builder.addFieldInt8(2, +enabled, +false);
}

static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, addressOffset, 0);
}

static addPort(builder:flatbuffers.Builder, port:number) {
  builder.addFieldInt16(4, port, 0);
}

static addTrackers(builder:flatbuffers.Builder, trackersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, trackersOffset, 0);
}

static createTrackersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTrackersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCustomOSCProfile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCustomOSCProfile(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, enabled:boolean, addressOffset:flatbuffers.Offset, port:number, trackersOffset:flatbuffers.Offset):flatbuffers.Offset {
  CustomOSCProfile.startCustomOSCProfile(builder);
  CustomOSCProfile.addId(builder, idOffset);
  CustomOSCProfile.addName(builder, nameOffset);
  CustomOSCProfile.addEnabled(builder, enabled);
  CustomOSCProfile.addAddress(builder, addressOffset);
  CustomOSCProfile.addPort(builder, port);
  CustomOSCProfile.addTrackers(builder, trackersOffset);
  return CustomOSCProfile.endCustomOSCProfile(builder);
}

unpack(): CustomOSCProfileT {
  return new CustomOSCProfileT(
    this.id(),
    this.name(),
    this.enabled(),
    this.address(),
    this.port(),
    this.bb!.createObjList<CustomOSCTrackerMapping, CustomOSCTrackerMappingT>(this.trackers.bind(this), this.trackersLength())
  );
}


unpackTo(_o: CustomOSCProfileT): void {
  _o.id = this.id();
  _o.name = this.name();
  _o.enabled = this.enabled();
  _o.address = this.address();
  _o.port = this.port();
  _o.trackers = this.bb!.createObjList<CustomOSCTrackerMapping, CustomOSCTrackerMappingT>(this.trackers.bind(this), this.trackersLength());
}
}

export class CustomOSCProfileT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null,
  public enabled: boolean = false,
  public address: string|Uint8Array|null = null,
  public port: number = 0,
  public trackers: (CustomOSCTrackerMappingT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const address = (this.address !== null ? builder.createString(this.address!) : 0);
  const trackers = CustomOSCProfile.createTrackersVector(builder, builder.createObjectOffsetList(this.trackers));

  return CustomOSCProfile.createCustomOSCProfile(builder,
    id,
    name,
    this.enabled,
    address,
    this.port,
    trackers
  );
}
}
