// automatically generated by the FlatBuffers compiler, do not modify

export enum DriverConnectionState {
  /**
   * No driver on this platform, for example Android.
   */
  UNSUPPORTED = 0,

  /**
   * Switched off in the driver settings, so nothing is listening for it.
   */
  DISABLED = 1,

  /**
   * Listening, but no driver has connected.
   */
  WAITING = 2,
  CONNECTED = 3
}
