// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Returns the current HMD height and returns an estimated full height (user height)
 */
export class HeightResponse implements flatbuffers.IUnpackableObject<HeightResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HeightResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHeightResponse(bb:flatbuffers.ByteBuffer, obj?:HeightResponse):HeightResponse {
  return (obj || new HeightResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHeightResponse(bb:flatbuffers.ByteBuffer, obj?:HeightResponse):HeightResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HeightResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

hmdHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

estimatedFullHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startHeightResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addHmdHeight(builder:flatbuffers.Builder, hmdHeight:number) {
  builder.addFieldFloat32(0, hmdHeight, 0.0);
}

static addEstimatedFullHeight(builder:flatbuffers.Builder, estimatedFullHeight:number) {
  builder.addFieldFloat32(1, estimatedFullHeight, 0.0);
}

static endHeightResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHeightResponse(builder:flatbuffers.Builder, hmdHeight:number, estimatedFullHeight:number):flatbuffers.Offset {
  HeightResponse.startHeightResponse(builder);
  HeightResponse.addHmdHeight(builder, hmdHeight);
  HeightResponse.addEstimatedFullHeight(builder, estimatedFullHeight);
  return HeightResponse.endHeightResponse(builder);
}

unpack(): HeightResponseT {
  return new HeightResponseT(
    this.hmdHeight(),
    this.estimatedFullHeight()
  );
}


unpackTo(_o: HeightResponseT): void {
  _o.hmdHeight = this.hmdHeight();
  _o.estimatedFullHeight = this.estimatedFullHeight();
}
}

export class HeightResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public hmdHeight: number = 0.0,
  public estimatedFullHeight: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return HeightResponse.createHeightResponse(builder,
    this.hmdHeight,
    this.estimatedFullHeight
  );
}
}
