// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { SerialDevice, SerialDeviceT } from '../../solarxr-protocol/rpc/serial-device.js';


export class SerialDevicesResponse implements flatbuffers.IUnpackableObject<SerialDevicesResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SerialDevicesResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSerialDevicesResponse(bb:flatbuffers.ByteBuffer, obj?:SerialDevicesResponse):SerialDevicesResponse {
  return (obj || new SerialDevicesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSerialDevicesResponse(bb:flatbuffers.ByteBuffer, obj?:SerialDevicesResponse):SerialDevicesResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SerialDevicesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

devices(index: number, obj?:SerialDevice):SerialDevice|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SerialDevice()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

devicesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSerialDevicesResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDevices(builder:flatbuffers.Builder, devicesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, devicesOffset, 0);
}

static createDevicesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDevicesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSerialDevicesResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSerialDevicesResponse(builder:flatbuffers.Builder, devicesOffset:flatbuffers.Offset):flatbuffers.Offset {
  SerialDevicesResponse.startSerialDevicesResponse(builder);
  SerialDevicesResponse.addDevices(builder, devicesOffset);
  return SerialDevicesResponse.endSerialDevicesResponse(builder);
}

unpack(): SerialDevicesResponseT {
  return new SerialDevicesResponseT(
    this.bb!.createObjList<SerialDevice, SerialDeviceT>(this.devices.bind(this), this.devicesLength())
  );
}


unpackTo(_o: SerialDevicesResponseT): void {
  _o.devices = this.bb!.createObjList<SerialDevice, SerialDeviceT>(this.devices.bind(this), this.devicesLength());
}
}

export class SerialDevicesResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public devices: (SerialDeviceT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const devices = SerialDevicesResponse.createDevicesVector(builder, builder.createObjectOffsetList(this.devices));

  return SerialDevicesResponse.createSerialDevicesResponse(builder,
    devices
  );
}
}
