// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Renews the client's hold on the ports it opened. A client that stops sending these loses them,
 * so a page that goes away without a CloseSerialRequest does not keep the ports locked
 */
export class SerialKeepaliveRequest implements flatbuffers.IUnpackableObject<SerialKeepaliveRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SerialKeepaliveRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSerialKeepaliveRequest(bb:flatbuffers.ByteBuffer, obj?:SerialKeepaliveRequest):SerialKeepaliveRequest {
  return (obj || new SerialKeepaliveRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSerialKeepaliveRequest(bb:flatbuffers.ByteBuffer, obj?:SerialKeepaliveRequest):SerialKeepaliveRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SerialKeepaliveRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startSerialKeepaliveRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endSerialKeepaliveRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSerialKeepaliveRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  SerialKeepaliveRequest.startSerialKeepaliveRequest(builder);
  return SerialKeepaliveRequest.endSerialKeepaliveRequest(builder);
}

unpack(): SerialKeepaliveRequestT {
  return new SerialKeepaliveRequestT();
}


unpackTo(_o: SerialKeepaliveRequestT): void {}
}

export class SerialKeepaliveRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return SerialKeepaliveRequest.createSerialKeepaliveRequest(builder);
}
}
