// automatically generated by the FlatBuffers compiler, do not modify

export enum SerialDeviceType {
  /**
   * A USB serial port whose vendor and product id are not recognized
   */
  UNKNOWN = 0,
  ESP_TRACKER = 1,
  HID_RECEIVER = 2,
  HID_TRACKER = 3
}
