// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Ratios for the skeletal model. Accepted values for them range from 0 to 1
 */
export class SkeletonRatios implements flatbuffers.IUnpackableObject<SkeletonRatiosT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SkeletonRatios {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSkeletonRatios(bb:flatbuffers.ByteBuffer, obj?:SkeletonRatios):SkeletonRatios {
  return (obj || new SkeletonRatios()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSkeletonRatios(bb:flatbuffers.ByteBuffer, obj?:SkeletonRatios):SkeletonRatios {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SkeletonRatios()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Compute missing spine bones as a ratio of the next available upper and lower bones.
 */
imputeSpineFromUpperToLower():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

/**
 * Computes the curvature between 2 adjacent missing spine bones. Higher = more curvature.
 */
imputeSpineCurvature():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

/**
 * How much to average the hip's yaw and roll with the upper legs'.
 */
interpolateHipWithUpperLegs():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

/**
 * How much to average the upper legs' roll with the lower legs'.
 */
interpolateUpperLegsTwistWithLowerLegs():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

/**
 * Strength of skating correction. Enabled via SkeletonToggles.skating_correction
 */
skatingCorrectionStrength():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

static startSkeletonRatios(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addImputeSpineFromUpperToLower(builder:flatbuffers.Builder, imputeSpineFromUpperToLower:number) {
  builder.addFieldFloat32(0, imputeSpineFromUpperToLower, 0);
}

static addImputeSpineCurvature(builder:flatbuffers.Builder, imputeSpineCurvature:number) {
  builder.addFieldFloat32(1, imputeSpineCurvature, 0);
}

static addInterpolateHipWithUpperLegs(builder:flatbuffers.Builder, interpolateHipWithUpperLegs:number) {
  builder.addFieldFloat32(2, interpolateHipWithUpperLegs, 0);
}

static addInterpolateUpperLegsTwistWithLowerLegs(builder:flatbuffers.Builder, interpolateUpperLegsTwistWithLowerLegs:number) {
  builder.addFieldFloat32(3, interpolateUpperLegsTwistWithLowerLegs, 0);
}

static addSkatingCorrectionStrength(builder:flatbuffers.Builder, skatingCorrectionStrength:number) {
  builder.addFieldFloat32(4, skatingCorrectionStrength, 0);
}

static endSkeletonRatios(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSkeletonRatios(builder:flatbuffers.Builder, imputeSpineFromUpperToLower:number|null, imputeSpineCurvature:number|null, interpolateHipWithUpperLegs:number|null, interpolateUpperLegsTwistWithLowerLegs:number|null, skatingCorrectionStrength:number|null):flatbuffers.Offset {
  SkeletonRatios.startSkeletonRatios(builder);
  if (imputeSpineFromUpperToLower !== null)
    SkeletonRatios.addImputeSpineFromUpperToLower(builder, imputeSpineFromUpperToLower);
  if (imputeSpineCurvature !== null)
    SkeletonRatios.addImputeSpineCurvature(builder, imputeSpineCurvature);
  if (interpolateHipWithUpperLegs !== null)
    SkeletonRatios.addInterpolateHipWithUpperLegs(builder, interpolateHipWithUpperLegs);
  if (interpolateUpperLegsTwistWithLowerLegs !== null)
    SkeletonRatios.addInterpolateUpperLegsTwistWithLowerLegs(builder, interpolateUpperLegsTwistWithLowerLegs);
  if (skatingCorrectionStrength !== null)
    SkeletonRatios.addSkatingCorrectionStrength(builder, skatingCorrectionStrength);
  return SkeletonRatios.endSkeletonRatios(builder);
}

unpack(): SkeletonRatiosT {
  return new SkeletonRatiosT(
    this.imputeSpineFromUpperToLower(),
    this.imputeSpineCurvature(),
    this.interpolateHipWithUpperLegs(),
    this.interpolateUpperLegsTwistWithLowerLegs(),
    this.skatingCorrectionStrength()
  );
}


unpackTo(_o: SkeletonRatiosT): void {
  _o.imputeSpineFromUpperToLower = this.imputeSpineFromUpperToLower();
  _o.imputeSpineCurvature = this.imputeSpineCurvature();
  _o.interpolateHipWithUpperLegs = this.interpolateHipWithUpperLegs();
  _o.interpolateUpperLegsTwistWithLowerLegs = this.interpolateUpperLegsTwistWithLowerLegs();
  _o.skatingCorrectionStrength = this.skatingCorrectionStrength();
}
}

export class SkeletonRatiosT implements flatbuffers.IGeneratedObject {
constructor(
  public imputeSpineFromUpperToLower: number|null = null,
  public imputeSpineCurvature: number|null = null,
  public interpolateHipWithUpperLegs: number|null = null,
  public interpolateUpperLegsTwistWithLowerLegs: number|null = null,
  public skatingCorrectionStrength: number|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return SkeletonRatios.createSkeletonRatios(builder,
    this.imputeSpineFromUpperToLower,
    this.imputeSpineCurvature,
    this.interpolateHipWithUpperLegs,
    this.interpolateUpperLegsTwistWithLowerLegs,
    this.skatingCorrectionStrength
  );
}
}
