// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Re-sending Start replaces the previous subscription, same semantics as
 * StartDataFeed (data_feed/data_feed.fbs) -- this is also how the GUI
 * changes which trackers it's monitoring, no separate config message.
 */
export class StartTelemetryRequest implements flatbuffers.IUnpackableObject<StartTelemetryRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartTelemetryRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartTelemetryRequest(bb:flatbuffers.ByteBuffer, obj?:StartTelemetryRequest):StartTelemetryRequest {
  return (obj || new StartTelemetryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartTelemetryRequest(bb:flatbuffers.ByteBuffer, obj?:StartTelemetryRequest):StartTelemetryRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartTelemetryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

deviceIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

deviceIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

deviceIdsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startStartTelemetryRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDeviceIds(builder:flatbuffers.Builder, deviceIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, deviceIdsOffset, 0);
}

static createDeviceIdsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createDeviceIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createDeviceIdsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startDeviceIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static endStartTelemetryRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStartTelemetryRequest(builder:flatbuffers.Builder, deviceIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  StartTelemetryRequest.startStartTelemetryRequest(builder);
  StartTelemetryRequest.addDeviceIds(builder, deviceIdsOffset);
  return StartTelemetryRequest.endStartTelemetryRequest(builder);
}

unpack(): StartTelemetryRequestT {
  return new StartTelemetryRequestT(
    this.bb!.createScalarList<number>(this.deviceIds.bind(this), this.deviceIdsLength())
  );
}


unpackTo(_o: StartTelemetryRequestT): void {
  _o.deviceIds = this.bb!.createScalarList<number>(this.deviceIds.bind(this), this.deviceIdsLength());
}
}

export class StartTelemetryRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public deviceIds: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const deviceIds = StartTelemetryRequest.createDeviceIdsVector(builder, this.deviceIds);

  return StartTelemetryRequest.createStartTelemetryRequest(builder,
    deviceIds
  );
}
}
