// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class StartUserHeightCalibration implements flatbuffers.IUnpackableObject<StartUserHeightCalibrationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartUserHeightCalibration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartUserHeightCalibration(bb:flatbuffers.ByteBuffer, obj?:StartUserHeightCalibration):StartUserHeightCalibration {
  return (obj || new StartUserHeightCalibration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartUserHeightCalibration(bb:flatbuffers.ByteBuffer, obj?:StartUserHeightCalibration):StartUserHeightCalibration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartUserHeightCalibration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startStartUserHeightCalibration(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endStartUserHeightCalibration(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStartUserHeightCalibration(builder:flatbuffers.Builder):flatbuffers.Offset {
  StartUserHeightCalibration.startStartUserHeightCalibration(builder);
  return StartUserHeightCalibration.endStartUserHeightCalibration(builder);
}

unpack(): StartUserHeightCalibrationT {
  return new StartUserHeightCalibrationT();
}


unpackTo(_o: StartUserHeightCalibrationT): void {}
}

export class StartUserHeightCalibrationT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StartUserHeightCalibration.createStartUserHeightCalibration(builder);
}
}
