// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { TrackerId, TrackerIdT } from '../../solarxr-protocol/datatypes/tracker-id.js';


/**
 * Tracker requires full reset
 */
export class StatusTrackerReset implements flatbuffers.IUnpackableObject<StatusTrackerResetT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StatusTrackerReset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStatusTrackerReset(bb:flatbuffers.ByteBuffer, obj?:StatusTrackerReset):StatusTrackerReset {
  return (obj || new StatusTrackerReset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStatusTrackerReset(bb:flatbuffers.ByteBuffer, obj?:StatusTrackerReset):StatusTrackerReset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StatusTrackerReset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

trackerId(index: number, obj?:TrackerId):TrackerId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TrackerId()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

trackerIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStatusTrackerReset(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTrackerId(builder:flatbuffers.Builder, trackerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, trackerIdOffset, 0);
}

static createTrackerIdVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTrackerIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStatusTrackerReset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStatusTrackerReset(builder:flatbuffers.Builder, trackerIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  StatusTrackerReset.startStatusTrackerReset(builder);
  StatusTrackerReset.addTrackerId(builder, trackerIdOffset);
  return StatusTrackerReset.endStatusTrackerReset(builder);
}

unpack(): StatusTrackerResetT {
  return new StatusTrackerResetT(
    this.bb!.createObjList<TrackerId, TrackerIdT>(this.trackerId.bind(this), this.trackerIdLength())
  );
}


unpackTo(_o: StatusTrackerResetT): void {
  _o.trackerId = this.bb!.createObjList<TrackerId, TrackerIdT>(this.trackerId.bind(this), this.trackerIdLength());
}
}

export class StatusTrackerResetT implements flatbuffers.IGeneratedObject {
constructor(
  public trackerId: (TrackerIdT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const trackerId = StatusTrackerReset.createTrackerIdVector(builder, builder.createObjectOffsetList(this.trackerId));

  return StatusTrackerReset.createStatusTrackerReset(builder,
    trackerId
  );
}
}
