// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class StopWifiProvisioningRequest implements flatbuffers.IUnpackableObject<StopWifiProvisioningRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StopWifiProvisioningRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStopWifiProvisioningRequest(bb:flatbuffers.ByteBuffer, obj?:StopWifiProvisioningRequest):StopWifiProvisioningRequest {
  return (obj || new StopWifiProvisioningRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStopWifiProvisioningRequest(bb:flatbuffers.ByteBuffer, obj?:StopWifiProvisioningRequest):StopWifiProvisioningRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StopWifiProvisioningRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startStopWifiProvisioningRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endStopWifiProvisioningRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStopWifiProvisioningRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  StopWifiProvisioningRequest.startStopWifiProvisioningRequest(builder);
  return StopWifiProvisioningRequest.endStopWifiProvisioningRequest(builder);
}

unpack(): StopWifiProvisioningRequestT {
  return new StopWifiProvisioningRequestT();
}


unpackTo(_o: StopWifiProvisioningRequestT): void {}
}

export class StopWifiProvisioningRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StopWifiProvisioningRequest.createStopWifiProvisioningRequest(builder);
}
}
