// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class TimeoutSettingsResponse implements flatbuffers.IUnpackableObject<TimeoutSettingsResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TimeoutSettingsResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTimeoutSettingsResponse(bb:flatbuffers.ByteBuffer, obj?:TimeoutSettingsResponse):TimeoutSettingsResponse {
  return (obj || new TimeoutSettingsResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTimeoutSettingsResponse(bb:flatbuffers.ByteBuffer, obj?:TimeoutSettingsResponse):TimeoutSettingsResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TimeoutSettingsResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

duration():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startTimeoutSettingsResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDuration(builder:flatbuffers.Builder, duration:number) {
  builder.addFieldFloat32(0, duration, 0.0);
}

static endTimeoutSettingsResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTimeoutSettingsResponse(builder:flatbuffers.Builder, duration:number):flatbuffers.Offset {
  TimeoutSettingsResponse.startTimeoutSettingsResponse(builder);
  TimeoutSettingsResponse.addDuration(builder, duration);
  return TimeoutSettingsResponse.endTimeoutSettingsResponse(builder);
}

unpack(): TimeoutSettingsResponseT {
  return new TimeoutSettingsResponseT(
    this.duration()
  );
}


unpackTo(_o: TimeoutSettingsResponseT): void {
  _o.duration = this.duration();
}
}

export class TimeoutSettingsResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public duration: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return TimeoutSettingsResponse.createTimeoutSettingsResponse(builder,
    this.duration
  );
}
}
