// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class TrackingChecklistRequest implements flatbuffers.IUnpackableObject<TrackingChecklistRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TrackingChecklistRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTrackingChecklistRequest(bb:flatbuffers.ByteBuffer, obj?:TrackingChecklistRequest):TrackingChecklistRequest {
  return (obj || new TrackingChecklistRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTrackingChecklistRequest(bb:flatbuffers.ByteBuffer, obj?:TrackingChecklistRequest):TrackingChecklistRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TrackingChecklistRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startTrackingChecklistRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endTrackingChecklistRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTrackingChecklistRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  TrackingChecklistRequest.startTrackingChecklistRequest(builder);
  return TrackingChecklistRequest.endTrackingChecklistRequest(builder);
}

unpack(): TrackingChecklistRequestT {
  return new TrackingChecklistRequestT();
}


unpackTo(_o: TrackingChecklistRequestT): void {}
}

export class TrackingChecklistRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return TrackingChecklistRequest.createTrackingChecklistRequest(builder);
}
}
