// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { TrackerProvisioningStatus } from '../../solarxr-protocol/rpc/tracker-provisioning-status.js';


export class TrackerProvisioningState implements flatbuffers.IUnpackableObject<TrackerProvisioningStateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TrackerProvisioningState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTrackerProvisioningState(bb:flatbuffers.ByteBuffer, obj?:TrackerProvisioningState):TrackerProvisioningState {
  return (obj || new TrackerProvisioningState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTrackerProvisioningState(bb:flatbuffers.ByteBuffer, obj?:TrackerProvisioningState):TrackerProvisioningState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TrackerProvisioningState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

port():string|null
port(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
port(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

macAddress():string|null
macAddress(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
macAddress(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

status():TrackerProvisioningStatus {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TrackerProvisioningStatus.SERIAL_INIT;
}

static startTrackerProvisioningState(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPort(builder:flatbuffers.Builder, portOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, portOffset, 0);
}

static addMacAddress(builder:flatbuffers.Builder, macAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, macAddressOffset, 0);
}

static addStatus(builder:flatbuffers.Builder, status:TrackerProvisioningStatus) {
  builder.addFieldInt8(2, status, TrackerProvisioningStatus.SERIAL_INIT);
}

static endTrackerProvisioningState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTrackerProvisioningState(builder:flatbuffers.Builder, portOffset:flatbuffers.Offset, macAddressOffset:flatbuffers.Offset, status:TrackerProvisioningStatus):flatbuffers.Offset {
  TrackerProvisioningState.startTrackerProvisioningState(builder);
  TrackerProvisioningState.addPort(builder, portOffset);
  TrackerProvisioningState.addMacAddress(builder, macAddressOffset);
  TrackerProvisioningState.addStatus(builder, status);
  return TrackerProvisioningState.endTrackerProvisioningState(builder);
}

unpack(): TrackerProvisioningStateT {
  return new TrackerProvisioningStateT(
    this.port(),
    this.macAddress(),
    this.status()
  );
}


unpackTo(_o: TrackerProvisioningStateT): void {
  _o.port = this.port();
  _o.macAddress = this.macAddress();
  _o.status = this.status();
}
}

export class TrackerProvisioningStateT implements flatbuffers.IGeneratedObject {
constructor(
  public port: string|Uint8Array|null = null,
  public macAddress: string|Uint8Array|null = null,
  public status: TrackerProvisioningStatus = TrackerProvisioningStatus.SERIAL_INIT
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const port = (this.port !== null ? builder.createString(this.port!) : 0);
  const macAddress = (this.macAddress !== null ? builder.createString(this.macAddress!) : 0);

  return TrackerProvisioningState.createTrackerProvisioningState(builder,
    port,
    macAddress,
    this.status
  );
}
}
