// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class UpdaterVersion implements flatbuffers.IUnpackableObject<UpdaterVersionT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdaterVersion {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdaterVersion(bb:flatbuffers.ByteBuffer, obj?:UpdaterVersion):UpdaterVersion {
  return (obj || new UpdaterVersion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdaterVersion(bb:flatbuffers.ByteBuffer, obj?:UpdaterVersion):UpdaterVersion {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdaterVersion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

version():string|null
version(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
version(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

changeLog():string|null
changeLog(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
changeLog(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startUpdaterVersion(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addVersion(builder:flatbuffers.Builder, versionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, versionOffset, 0);
}

static addChangeLog(builder:flatbuffers.Builder, changeLogOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, changeLogOffset, 0);
}

static endUpdaterVersion(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUpdaterVersion(builder:flatbuffers.Builder, versionOffset:flatbuffers.Offset, changeLogOffset:flatbuffers.Offset):flatbuffers.Offset {
  UpdaterVersion.startUpdaterVersion(builder);
  UpdaterVersion.addVersion(builder, versionOffset);
  UpdaterVersion.addChangeLog(builder, changeLogOffset);
  return UpdaterVersion.endUpdaterVersion(builder);
}

unpack(): UpdaterVersionT {
  return new UpdaterVersionT(
    this.version(),
    this.changeLog()
  );
}


unpackTo(_o: UpdaterVersionT): void {
  _o.version = this.version();
  _o.changeLog = this.changeLog();
}
}

export class UpdaterVersionT implements flatbuffers.IGeneratedObject {
constructor(
  public version: string|Uint8Array|null = null,
  public changeLog: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const version = (this.version !== null ? builder.createString(this.version!) : 0);
  const changeLog = (this.changeLog !== null ? builder.createString(this.changeLog!) : 0);

  return UpdaterVersion.createUpdaterVersion(builder,
    version,
    changeLog
  );
}
}
