// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.firmware.data_feed;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class DataFeedUpdateT {
  private solarxr_protocol.firmware.data_feed.device_data.DeviceDataT[] devices;

  public solarxr_protocol.firmware.data_feed.device_data.DeviceDataT[] getDevices() { return devices; }

  public void setDevices(solarxr_protocol.firmware.data_feed.device_data.DeviceDataT[] devices) { this.devices = devices; }


  public DataFeedUpdateT() {
    this.devices = null;
  }
}

