// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AssignTrackerRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static AssignTrackerRequest getRootAsAssignTrackerRequest(ByteBuffer _bb) { return getRootAsAssignTrackerRequest(_bb, new AssignTrackerRequest()); }
  public static AssignTrackerRequest getRootAsAssignTrackerRequest(ByteBuffer _bb, AssignTrackerRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AssignTrackerRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int trackerId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int bodyPosition() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public solarxr_protocol.datatypes.math.Quat mountingOrientation() { return mountingOrientation(new solarxr_protocol.datatypes.math.Quat()); }
  public solarxr_protocol.datatypes.math.Quat mountingOrientation(solarxr_protocol.datatypes.math.Quat obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public String displayName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer displayNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer displayNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static void startAssignTrackerRequest(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addTrackerId(FlatBufferBuilder builder, int trackerId) { builder.addShort(0, (short) trackerId, (short) 0); }
  public static void addBodyPosition(FlatBufferBuilder builder, int bodyPosition) { builder.addByte(1, (byte) bodyPosition, (byte) 0); }
  public static void addMountingOrientation(FlatBufferBuilder builder, int mountingOrientationOffset) { builder.addStruct(2, mountingOrientationOffset, 0); }
  public static void addDisplayName(FlatBufferBuilder builder, int displayNameOffset) { builder.addOffset(3, displayNameOffset, 0); }
  public static int endAssignTrackerRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AssignTrackerRequest get(int j) { return get(new AssignTrackerRequest(), j); }
    public AssignTrackerRequest get(AssignTrackerRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public AssignTrackerRequestT unpack() {
    AssignTrackerRequestT _o = new AssignTrackerRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(AssignTrackerRequestT _o) {
    int _oTrackerId = trackerId();
    _o.setTrackerId(_oTrackerId);
    int _oBodyPosition = bodyPosition();
    _o.setBodyPosition(_oBodyPosition);
    if (mountingOrientation() != null) mountingOrientation().unpackTo(_o.getMountingOrientation());
    else _o.setMountingOrientation(null);
    String _oDisplayName = displayName();
    _o.setDisplayName(_oDisplayName);
  }
  public static int pack(FlatBufferBuilder builder, AssignTrackerRequestT _o) {
    if (_o == null) return 0;
    int _displayName = _o.getDisplayName() == null ? 0 : builder.createString(_o.getDisplayName());
    startAssignTrackerRequest(builder);
    addTrackerId(builder, _o.getTrackerId());
    addBodyPosition(builder, _o.getBodyPosition());
    addMountingOrientation(builder, solarxr_protocol.datatypes.math.Quat.pack(builder, _o.getMountingOrientation()));
    addDisplayName(builder, _displayName);
    return endAssignTrackerRequest(builder);
  }
}

