// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Stops the current recording, using it as far as it has been recorded
 */
@SuppressWarnings("unused")
public final class AutoBoneStopRecordingRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static AutoBoneStopRecordingRequest getRootAsAutoBoneStopRecordingRequest(ByteBuffer _bb) { return getRootAsAutoBoneStopRecordingRequest(_bb, new AutoBoneStopRecordingRequest()); }
  public static AutoBoneStopRecordingRequest getRootAsAutoBoneStopRecordingRequest(ByteBuffer _bb, AutoBoneStopRecordingRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AutoBoneStopRecordingRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startAutoBoneStopRecordingRequest(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endAutoBoneStopRecordingRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AutoBoneStopRecordingRequest get(int j) { return get(new AutoBoneStopRecordingRequest(), j); }
    public AutoBoneStopRecordingRequest get(AutoBoneStopRecordingRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public AutoBoneStopRecordingRequestT unpack() {
    AutoBoneStopRecordingRequestT _o = new AutoBoneStopRecordingRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(AutoBoneStopRecordingRequestT _o) {
  }
  public static int pack(FlatBufferBuilder builder, AutoBoneStopRecordingRequestT _o) {
    if (_o == null) return 0;
    startAutoBoneStopRecordingRequest(builder);
    return endAutoBoneStopRecordingRequest(builder);
  }
}

