// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * If no tracker ID is given, it's the setting for every tracker/device
 */
@SuppressWarnings("unused")
public final class ChangeMagToggleRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static ChangeMagToggleRequest getRootAsChangeMagToggleRequest(ByteBuffer _bb) { return getRootAsChangeMagToggleRequest(_bb, new ChangeMagToggleRequest()); }
  public static ChangeMagToggleRequest getRootAsChangeMagToggleRequest(ByteBuffer _bb, ChangeMagToggleRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ChangeMagToggleRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.datatypes.TrackerId trackerId() { return trackerId(new solarxr_protocol.datatypes.TrackerId()); }
  public solarxr_protocol.datatypes.TrackerId trackerId(solarxr_protocol.datatypes.TrackerId obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public boolean enable() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createChangeMagToggleRequest(FlatBufferBuilder builder,
      int trackerIdOffset,
      boolean enable) {
    builder.startTable(2);
    ChangeMagToggleRequest.addTrackerId(builder, trackerIdOffset);
    ChangeMagToggleRequest.addEnable(builder, enable);
    return ChangeMagToggleRequest.endChangeMagToggleRequest(builder);
  }

  public static void startChangeMagToggleRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addTrackerId(FlatBufferBuilder builder, int trackerIdOffset) { builder.addOffset(0, trackerIdOffset, 0); }
  public static void addEnable(FlatBufferBuilder builder, boolean enable) { builder.addBoolean(1, enable, false); }
  public static int endChangeMagToggleRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ChangeMagToggleRequest get(int j) { return get(new ChangeMagToggleRequest(), j); }
    public ChangeMagToggleRequest get(ChangeMagToggleRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ChangeMagToggleRequestT unpack() {
    ChangeMagToggleRequestT _o = new ChangeMagToggleRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ChangeMagToggleRequestT _o) {
    if (trackerId() != null) _o.setTrackerId(trackerId().unpack());
    else _o.setTrackerId(null);
    boolean _oEnable = enable();
    _o.setEnable(_oEnable);
  }
  public static int pack(FlatBufferBuilder builder, ChangeMagToggleRequestT _o) {
    if (_o == null) return 0;
    int _trackerId = _o.getTrackerId() == null ? 0 : solarxr_protocol.datatypes.TrackerId.pack(builder, _o.getTrackerId());
    return createChangeMagToggleRequest(
      builder,
      _trackerId,
      _o.getEnable());
  }
}

