// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ChangeTimeoutSettingsRequestT {
  private float delay;

  public float getDelay() { return delay; }

  public void setDelay(float delay) { this.delay = delay; }


  public ChangeTimeoutSettingsRequestT() {
    this.delay = 0.0f;
  }
}

