// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ChangeErrorReportingSettingsRequestT {
  private int consent;

  public int getConsent() { return consent; }

  public void setConsent(int consent) { this.consent = consent; }


  public ChangeErrorReportingSettingsRequestT() {
    this.consent = 0;
  }
}

