// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChangeVRMSettingsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static ChangeVRMSettingsRequest getRootAsChangeVRMSettingsRequest(ByteBuffer _bb) { return getRootAsChangeVRMSettingsRequest(_bb, new ChangeVRMSettingsRequest()); }
  public static ChangeVRMSettingsRequest getRootAsChangeVRMSettingsRequest(ByteBuffer _bb, ChangeVRMSettingsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ChangeVRMSettingsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String vrmJson() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer vrmJsonAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer vrmJsonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createChangeVRMSettingsRequest(FlatBufferBuilder builder,
      int vrmJsonOffset) {
    builder.startTable(1);
    ChangeVRMSettingsRequest.addVrmJson(builder, vrmJsonOffset);
    return ChangeVRMSettingsRequest.endChangeVRMSettingsRequest(builder);
  }

  public static void startChangeVRMSettingsRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addVrmJson(FlatBufferBuilder builder, int vrmJsonOffset) { builder.addOffset(0, vrmJsonOffset, 0); }
  public static int endChangeVRMSettingsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ChangeVRMSettingsRequest get(int j) { return get(new ChangeVRMSettingsRequest(), j); }
    public ChangeVRMSettingsRequest get(ChangeVRMSettingsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ChangeVRMSettingsRequestT unpack() {
    ChangeVRMSettingsRequestT _o = new ChangeVRMSettingsRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ChangeVRMSettingsRequestT _o) {
    String _oVrmJson = vrmJson();
    _o.setVrmJson(_oVrmJson);
  }
  public static int pack(FlatBufferBuilder builder, ChangeVRMSettingsRequestT _o) {
    if (_o == null) return 0;
    int _vrmJson = _o.getVrmJson() == null ? 0 : builder.createString(_o.getVrmJson());
    return createChangeVRMSettingsRequest(
      builder,
      _vrmJson);
  }
}

