// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ChangeModelSettingsRequestT {
  private solarxr_protocol.rpc.settings.ModelTogglesT toggles;
  private solarxr_protocol.rpc.settings.ModelRatiosT ratios;
  private solarxr_protocol.rpc.settings.LegTweaksSettingsT legTweaks;
  private solarxr_protocol.rpc.settings.SkeletonHeightT skeletonHeight;
  private solarxr_protocol.rpc.settings.FilteringSettingsT filtering;

  public solarxr_protocol.rpc.settings.ModelTogglesT getToggles() { return toggles; }

  public void setToggles(solarxr_protocol.rpc.settings.ModelTogglesT toggles) { this.toggles = toggles; }

  public solarxr_protocol.rpc.settings.ModelRatiosT getRatios() { return ratios; }

  public void setRatios(solarxr_protocol.rpc.settings.ModelRatiosT ratios) { this.ratios = ratios; }

  public solarxr_protocol.rpc.settings.LegTweaksSettingsT getLegTweaks() { return legTweaks; }

  public void setLegTweaks(solarxr_protocol.rpc.settings.LegTweaksSettingsT legTweaks) { this.legTweaks = legTweaks; }

  public solarxr_protocol.rpc.settings.SkeletonHeightT getSkeletonHeight() { return skeletonHeight; }

  public void setSkeletonHeight(solarxr_protocol.rpc.settings.SkeletonHeightT skeletonHeight) { this.skeletonHeight = skeletonHeight; }

  public solarxr_protocol.rpc.settings.FilteringSettingsT getFiltering() { return filtering; }

  public void setFiltering(solarxr_protocol.rpc.settings.FilteringSettingsT filtering) { this.filtering = filtering; }


  public ChangeModelSettingsRequestT() {
    this.toggles = null;
    this.ratios = null;
    this.legTweaks = null;
    this.skeletonHeight = null;
    this.filtering = null;
  }
}

