// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ChangeDongleSettingsRequestT {
  private int dongleId;
  private String displayName;

  public int getDongleId() { return dongleId; }

  public void setDongleId(int dongleId) { this.dongleId = dongleId; }

  public String getDisplayName() { return displayName; }

  public void setDisplayName(String displayName) { this.displayName = displayName; }


  public ChangeDongleSettingsRequestT() {
    this.dongleId = 0;
    this.displayName = null;
  }
}

