// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ClearDriftCompensationRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static ClearDriftCompensationRequest getRootAsClearDriftCompensationRequest(ByteBuffer _bb) { return getRootAsClearDriftCompensationRequest(_bb, new ClearDriftCompensationRequest()); }
  public static ClearDriftCompensationRequest getRootAsClearDriftCompensationRequest(ByteBuffer _bb, ClearDriftCompensationRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ClearDriftCompensationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startClearDriftCompensationRequest(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endClearDriftCompensationRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ClearDriftCompensationRequest get(int j) { return get(new ClearDriftCompensationRequest(), j); }
    public ClearDriftCompensationRequest get(ClearDriftCompensationRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ClearDriftCompensationRequestT unpack() {
    ClearDriftCompensationRequestT _o = new ClearDriftCompensationRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ClearDriftCompensationRequestT _o) {
  }
  public static int pack(FlatBufferBuilder builder, ClearDriftCompensationRequestT _o) {
    if (_o == null) return 0;
    startClearDriftCompensationRequest(builder);
    return endClearDriftCompensationRequest(builder);
  }
}

