// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class FirmwarePartT {
  private String url;
  private long offset;
  private String digest;

  public String getUrl() { return url; }

  public void setUrl(String url) { this.url = url; }

  public long getOffset() { return offset; }

  public void setOffset(long offset) { this.offset = offset; }

  public String getDigest() { return digest; }

  public void setDigest(String digest) { this.digest = digest; }


  public FirmwarePartT() {
    this.url = null;
    this.offset = 0L;
    this.digest = null;
  }
}

