// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class FlightListExtraData {
  private FlightListExtraData() { }
  public static final byte NONE = 0;
  public static final byte FlightListTrackerReset = 1;
  public static final byte FlightListTrackerError = 2;
  public static final byte FlightListSteamVRDisconnected = 3;
  public static final byte FlightListUnassignedHMD = 4;
  public static final byte FlightListNeedCalibration = 5;

  public static final String[] names = { "NONE", "FlightListTrackerReset", "FlightListTrackerError", "FlightListSteamVRDisconnected", "FlightListUnassignedHMD", "FlightListNeedCalibration", };

  public static String name(int e) { return names[e]; }
}

