// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HIDSettings extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static HIDSettings getRootAsHIDSettings(ByteBuffer _bb) { return getRootAsHIDSettings(_bb, new HIDSettings()); }
  public static HIDSettings getRootAsHIDSettings(ByteBuffer _bb, HIDSettings obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HIDSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean trackersOverHid() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createHIDSettings(FlatBufferBuilder builder,
      boolean trackersOverHid) {
    builder.startTable(1);
    HIDSettings.addTrackersOverHid(builder, trackersOverHid);
    return HIDSettings.endHIDSettings(builder);
  }

  public static void startHIDSettings(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTrackersOverHid(FlatBufferBuilder builder, boolean trackersOverHid) { builder.addBoolean(0, trackersOverHid, false); }
  public static int endHIDSettings(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HIDSettings get(int j) { return get(new HIDSettings(), j); }
    public HIDSettings get(HIDSettings obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public HIDSettingsT unpack() {
    HIDSettingsT _o = new HIDSettingsT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(HIDSettingsT _o) {
    boolean _oTrackersOverHid = trackersOverHid();
    _o.setTrackersOverHid(_oTrackersOverHid);
  }
  public static int pack(FlatBufferBuilder builder, HIDSettingsT _o) {
    if (_o == null) return 0;
    return createHIDSettings(
      builder,
      _o.getTrackersOverHid());
  }
}

