// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class LegTweaksTmpChangeT {
  private Boolean floorClip;
  private Boolean skatingCorrection;
  private Boolean toeSnap;
  private Boolean footPlant;

  public Boolean getFloorClip() { return floorClip; }

  public void setFloorClip(Boolean floorClip) { this.floorClip = floorClip; }

  public Boolean getSkatingCorrection() { return skatingCorrection; }

  public void setSkatingCorrection(Boolean skatingCorrection) { this.skatingCorrection = skatingCorrection; }

  public Boolean getToeSnap() { return toeSnap; }

  public void setToeSnap(Boolean toeSnap) { this.toeSnap = toeSnap; }

  public Boolean getFootPlant() { return footPlant; }

  public void setFootPlant(Boolean footPlant) { this.footPlant = footPlant; }


  public LegTweaksTmpChangeT() {
    this.floorClip = null;
    this.skatingCorrection = null;
    this.toeSnap = null;
    this.footPlant = null;
  }
}

