// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class RecordBVHRequestT {
  private boolean stop;
  private String filePath;
  private String folderPath;

  public boolean getStop() { return stop; }

  public void setStop(boolean stop) { this.stop = stop; }

  public String getFilePath() { return filePath; }

  public void setFilePath(String filePath) { this.filePath = filePath; }

  public String getFolderPath() { return folderPath; }

  public void setFolderPath(String folderPath) { this.folderPath = folderPath; }


  public RecordBVHRequestT() {
    this.stop = false;
    this.filePath = null;
    this.folderPath = null;
  }
}

