// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResetStatusResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static ResetStatusResponse getRootAsResetStatusResponse(ByteBuffer _bb) { return getRootAsResetStatusResponse(_bb, new ResetStatusResponse()); }
  public static ResetStatusResponse getRootAsResetStatusResponse(ByteBuffer _bb, ResetStatusResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ResetStatusResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int resetType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int lifecycle() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  /**
   * The body parts reset / being reset
   */
  public int bodyParts(int j) { int o = __offset(8); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int bodyPartsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector bodyPartsVector() { return bodyPartsVector(new ByteVector()); }
  public ByteVector bodyPartsVector(ByteVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer bodyPartsAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer bodyPartsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public byte detailType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table detail(Table obj) { int o = __offset(12); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createResetStatusResponse(FlatBufferBuilder builder,
      int resetType,
      int lifecycle,
      int bodyPartsOffset,
      byte detailType,
      int detailOffset) {
    builder.startTable(5);
    ResetStatusResponse.addDetail(builder, detailOffset);
    ResetStatusResponse.addBodyParts(builder, bodyPartsOffset);
    ResetStatusResponse.addDetailType(builder, detailType);
    ResetStatusResponse.addLifecycle(builder, lifecycle);
    ResetStatusResponse.addResetType(builder, resetType);
    return ResetStatusResponse.endResetStatusResponse(builder);
  }

  public static void startResetStatusResponse(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addResetType(FlatBufferBuilder builder, int resetType) { builder.addByte(0, (byte) resetType, (byte) 0); }
  public static void addLifecycle(FlatBufferBuilder builder, int lifecycle) { builder.addByte(1, (byte) lifecycle, (byte) 0); }
  public static void addBodyParts(FlatBufferBuilder builder, int bodyPartsOffset) { builder.addOffset(2, bodyPartsOffset, 0); }
  public static int createBodyPartsVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createBodyPartsVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startBodyPartsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addDetailType(FlatBufferBuilder builder, byte detailType) { builder.addByte(3, detailType, 0); }
  public static void addDetail(FlatBufferBuilder builder, int detailOffset) { builder.addOffset(4, detailOffset, 0); }
  public static int endResetStatusResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ResetStatusResponse get(int j) { return get(new ResetStatusResponse(), j); }
    public ResetStatusResponse get(ResetStatusResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ResetStatusResponseT unpack() {
    ResetStatusResponseT _o = new ResetStatusResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ResetStatusResponseT _o) {
    int _oResetType = resetType();
    _o.setResetType(_oResetType);
    int _oLifecycle = lifecycle();
    _o.setLifecycle(_oLifecycle);
    int[] _oBodyParts = new int[bodyPartsLength()];
    for (int _j = 0; _j < bodyPartsLength(); ++_j) {_oBodyParts[_j] = bodyParts(_j);}
    _o.setBodyParts(_oBodyParts);
    solarxr_protocol.rpc.ResetDetailUnion _oDetail = new solarxr_protocol.rpc.ResetDetailUnion();
    byte _oDetailType = detailType();
    _oDetail.setType(_oDetailType);
    Table _oDetailValue;
    switch (_oDetailType) {
      case solarxr_protocol.rpc.ResetDetail.CountdownDetail:
        _oDetailValue = detail(new solarxr_protocol.rpc.CountdownDetail());
        _oDetail.setValue(_oDetailValue != null ? ((solarxr_protocol.rpc.CountdownDetail) _oDetailValue).unpack() : null);
        break;
      case solarxr_protocol.rpc.ResetDetail.StepMountingDetail:
        _oDetailValue = detail(new solarxr_protocol.rpc.StepMountingDetail());
        _oDetail.setValue(_oDetailValue != null ? ((solarxr_protocol.rpc.StepMountingDetail) _oDetailValue).unpack() : null);
        break;
      default: break;
    }
    _o.setDetail(_oDetail);
  }
  public static int pack(FlatBufferBuilder builder, ResetStatusResponseT _o) {
    if (_o == null) return 0;
    int _bodyParts = 0;
    if (_o.getBodyParts() != null) {
      byte[] __bodyParts = new byte[_o.getBodyParts().length];
      int _j = 0;
      for (int _e : _o.getBodyParts()) { __bodyParts[_j] = (byte) _e; _j++;}
      _bodyParts = createBodyPartsVector(builder, __bodyParts);
    }
    byte _detailType = _o.getDetail() == null ? solarxr_protocol.rpc.ResetDetail.NONE : _o.getDetail().getType();
    int _detail = _o.getDetail() == null ? 0 : solarxr_protocol.rpc.ResetDetailUnion.pack(builder, _o.getDetail());
    return createResetStatusResponse(
      builder,
      _o.getResetType(),
      _o.getLifecycle(),
      _bodyParts,
      _detailType,
      _detail);
  }
}

