// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class RoutingOutputState {
  private RoutingOutputState() { }
  /**
   * Does not exist on this platform, for example the driver on Android.
   */
  public static final int UNSUPPORTED = 0;
  /**
   * Switched off in its own config, or no driver is connected.
   */
  public static final int INACTIVE = 1;
  /**
   * Known to be reaching something: a driver is connected, or a target was found.
   */
  public static final int ACTIVE = 2;
  /**
   * Switched on, but nothing confirms anything is listening. Routed to all the
   * same, so the bones are already in place once something does listen.
   */
  public static final int ENABLED = 3;

  public static final String[] names = { "UNSUPPORTED", "INACTIVE", "ACTIVE", "ENABLED", };

  public static String name(int e) { return names[e]; }
}

