// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class SaveFileNotificationT {
  private int[] data;
  private String mimeType;
  private String fileExtension;
  private Integer expectedDir;
  private String expectedFilename;

  public int[] getData() { return data; }

  public void setData(int[] data) { this.data = data; }

  public String getMimeType() { return mimeType; }

  public void setMimeType(String mimeType) { this.mimeType = mimeType; }

  public String getFileExtension() { return fileExtension; }

  public void setFileExtension(String fileExtension) { this.fileExtension = fileExtension; }

  public Integer getExpectedDir() { return expectedDir; }

  public void setExpectedDir(Integer expectedDir) { this.expectedDir = expectedDir; }

  public String getExpectedFilename() { return expectedFilename; }

  public void setExpectedFilename(String expectedFilename) { this.expectedFilename = expectedFilename; }


  public SaveFileNotificationT() {
    this.data = null;
    this.mimeType = null;
    this.fileExtension = null;
    this.expectedDir = null;
    this.expectedFilename = null;
  }
}

