// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * SteamVR bridge is disconnected
 */
@SuppressWarnings("unused")
public final class StatusSteamVRDisconnected extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static StatusSteamVRDisconnected getRootAsStatusSteamVRDisconnected(ByteBuffer _bb) { return getRootAsStatusSteamVRDisconnected(_bb, new StatusSteamVRDisconnected()); }
  public static StatusSteamVRDisconnected getRootAsStatusSteamVRDisconnected(ByteBuffer _bb, StatusSteamVRDisconnected obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StatusSteamVRDisconnected __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startStatusSteamVRDisconnected(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endStatusSteamVRDisconnected(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StatusSteamVRDisconnected get(int j) { return get(new StatusSteamVRDisconnected(), j); }
    public StatusSteamVRDisconnected get(StatusSteamVRDisconnected obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public StatusSteamVRDisconnectedT unpack() {
    StatusSteamVRDisconnectedT _o = new StatusSteamVRDisconnectedT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(StatusSteamVRDisconnectedT _o) {
  }
  public static int pack(FlatBufferBuilder builder, StatusSteamVRDisconnectedT _o) {
    if (_o == null) return 0;
    startStatusSteamVRDisconnected(builder);
    return endStatusSteamVRDisconnected(builder);
  }
}

