// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class StatusMessageT {
  private long id;
  private boolean prioritized;
  private solarxr_protocol.rpc.StatusDataUnion data;

  public long getId() { return id; }

  public void setId(long id) { this.id = id; }

  public boolean getPrioritized() { return prioritized; }

  public void setPrioritized(boolean prioritized) { this.prioritized = prioritized; }

  public solarxr_protocol.rpc.StatusDataUnion getData() { return data; }

  public void setData(solarxr_protocol.rpc.StatusDataUnion data) { this.data = data; }


  public StatusMessageT() {
    this.id = 0L;
    this.prioritized = false;
    this.data = null;
  }
}

