// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class StatusSystemResponseT {
  private solarxr_protocol.rpc.StatusMessageT[] currentStatuses;

  public solarxr_protocol.rpc.StatusMessageT[] getCurrentStatuses() { return currentStatuses; }

  public void setCurrentStatuses(solarxr_protocol.rpc.StatusMessageT[] currentStatuses) { this.currentStatuses = currentStatuses; }


  public StatusSystemResponseT() {
    this.currentStatuses = null;
  }
}

