// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TapDetectionSettingsResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static TapDetectionSettingsResponse getRootAsTapDetectionSettingsResponse(ByteBuffer _bb) { return getRootAsTapDetectionSettingsResponse(_bb, new TapDetectionSettingsResponse()); }
  public static TapDetectionSettingsResponse getRootAsTapDetectionSettingsResponse(ByteBuffer _bb, TapDetectionSettingsResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TapDetectionSettingsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean hasFullResetDelay() { return 0 != __offset(4); }
  public float fullResetDelay() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0f; }
  public boolean hasFullResetEnabled() { return 0 != __offset(6); }
  public boolean fullResetEnabled() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean hasFullResetTaps() { return 0 != __offset(8); }
  public int fullResetTaps() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean hasYawResetDelay() { return 0 != __offset(10); }
  public float yawResetDelay() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0f; }
  public boolean hasYawResetEnabled() { return 0 != __offset(12); }
  public boolean yawResetEnabled() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean hasYawResetTaps() { return 0 != __offset(14); }
  public int yawResetTaps() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean hasMountingResetDelay() { return 0 != __offset(16); }
  public float mountingResetDelay() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0f; }
  public boolean hasMountingResetEnabled() { return 0 != __offset(18); }
  public boolean mountingResetEnabled() { int o = __offset(18); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean hasMountingResetTaps() { return 0 != __offset(20); }
  public int mountingResetTaps() { int o = __offset(20); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean hasNumberTrackersOverThreshold() { return 0 != __offset(22); }
  public int numberTrackersOverThreshold() { int o = __offset(22); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean hasYawResetBoneId() { return 0 != __offset(24); }
  public int yawResetBoneId() { int o = __offset(24); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean hasFullResetBoneId() { return 0 != __offset(26); }
  public int fullResetBoneId() { int o = __offset(26); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean hasMountingResetBoneId() { return 0 != __offset(28); }
  public int mountingResetBoneId() { int o = __offset(28); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createTapDetectionSettingsResponse(FlatBufferBuilder builder,
      float fullResetDelay,
      boolean fullResetEnabled,
      int fullResetTaps,
      float yawResetDelay,
      boolean yawResetEnabled,
      int yawResetTaps,
      float mountingResetDelay,
      boolean mountingResetEnabled,
      int mountingResetTaps,
      int numberTrackersOverThreshold,
      int yawResetBoneId,
      int fullResetBoneId,
      int mountingResetBoneId) {
    builder.startTable(13);
    TapDetectionSettingsResponse.addMountingResetDelay(builder, mountingResetDelay);
    TapDetectionSettingsResponse.addYawResetDelay(builder, yawResetDelay);
    TapDetectionSettingsResponse.addFullResetDelay(builder, fullResetDelay);
    TapDetectionSettingsResponse.addMountingResetBoneId(builder, mountingResetBoneId);
    TapDetectionSettingsResponse.addFullResetBoneId(builder, fullResetBoneId);
    TapDetectionSettingsResponse.addYawResetBoneId(builder, yawResetBoneId);
    TapDetectionSettingsResponse.addNumberTrackersOverThreshold(builder, numberTrackersOverThreshold);
    TapDetectionSettingsResponse.addMountingResetTaps(builder, mountingResetTaps);
    TapDetectionSettingsResponse.addMountingResetEnabled(builder, mountingResetEnabled);
    TapDetectionSettingsResponse.addYawResetTaps(builder, yawResetTaps);
    TapDetectionSettingsResponse.addYawResetEnabled(builder, yawResetEnabled);
    TapDetectionSettingsResponse.addFullResetTaps(builder, fullResetTaps);
    TapDetectionSettingsResponse.addFullResetEnabled(builder, fullResetEnabled);
    return TapDetectionSettingsResponse.endTapDetectionSettingsResponse(builder);
  }

  public static void startTapDetectionSettingsResponse(FlatBufferBuilder builder) { builder.startTable(13); }
  public static void addFullResetDelay(FlatBufferBuilder builder, float fullResetDelay) { builder.addFloat(0, fullResetDelay, 0f); }
  public static void addFullResetEnabled(FlatBufferBuilder builder, boolean fullResetEnabled) { builder.addBoolean(1, fullResetEnabled, false); }
  public static void addFullResetTaps(FlatBufferBuilder builder, int fullResetTaps) { builder.addByte(2, (byte) fullResetTaps, (byte) 0); }
  public static void addYawResetDelay(FlatBufferBuilder builder, float yawResetDelay) { builder.addFloat(3, yawResetDelay, 0f); }
  public static void addYawResetEnabled(FlatBufferBuilder builder, boolean yawResetEnabled) { builder.addBoolean(4, yawResetEnabled, false); }
  public static void addYawResetTaps(FlatBufferBuilder builder, int yawResetTaps) { builder.addByte(5, (byte) yawResetTaps, (byte) 0); }
  public static void addMountingResetDelay(FlatBufferBuilder builder, float mountingResetDelay) { builder.addFloat(6, mountingResetDelay, 0f); }
  public static void addMountingResetEnabled(FlatBufferBuilder builder, boolean mountingResetEnabled) { builder.addBoolean(7, mountingResetEnabled, false); }
  public static void addMountingResetTaps(FlatBufferBuilder builder, int mountingResetTaps) { builder.addByte(8, (byte) mountingResetTaps, (byte) 0); }
  public static void addNumberTrackersOverThreshold(FlatBufferBuilder builder, int numberTrackersOverThreshold) { builder.addByte(9, (byte) numberTrackersOverThreshold, (byte) 0); }
  public static void addYawResetBoneId(FlatBufferBuilder builder, int yawResetBoneId) { builder.addShort(10, (short) yawResetBoneId, (short) 0); }
  public static void addFullResetBoneId(FlatBufferBuilder builder, int fullResetBoneId) { builder.addShort(11, (short) fullResetBoneId, (short) 0); }
  public static void addMountingResetBoneId(FlatBufferBuilder builder, int mountingResetBoneId) { builder.addShort(12, (short) mountingResetBoneId, (short) 0); }
  public static int endTapDetectionSettingsResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TapDetectionSettingsResponse get(int j) { return get(new TapDetectionSettingsResponse(), j); }
    public TapDetectionSettingsResponse get(TapDetectionSettingsResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public TapDetectionSettingsResponseT unpack() {
    TapDetectionSettingsResponseT _o = new TapDetectionSettingsResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(TapDetectionSettingsResponseT _o) {
    Float _oFullResetDelay = hasFullResetDelay() ? fullResetDelay() : null;
    _o.setFullResetDelay(_oFullResetDelay);
    Boolean _oFullResetEnabled = hasFullResetEnabled() ? fullResetEnabled() : null;
    _o.setFullResetEnabled(_oFullResetEnabled);
    Integer _oFullResetTaps = hasFullResetTaps() ? fullResetTaps() : null;
    _o.setFullResetTaps(_oFullResetTaps);
    Float _oYawResetDelay = hasYawResetDelay() ? yawResetDelay() : null;
    _o.setYawResetDelay(_oYawResetDelay);
    Boolean _oYawResetEnabled = hasYawResetEnabled() ? yawResetEnabled() : null;
    _o.setYawResetEnabled(_oYawResetEnabled);
    Integer _oYawResetTaps = hasYawResetTaps() ? yawResetTaps() : null;
    _o.setYawResetTaps(_oYawResetTaps);
    Float _oMountingResetDelay = hasMountingResetDelay() ? mountingResetDelay() : null;
    _o.setMountingResetDelay(_oMountingResetDelay);
    Boolean _oMountingResetEnabled = hasMountingResetEnabled() ? mountingResetEnabled() : null;
    _o.setMountingResetEnabled(_oMountingResetEnabled);
    Integer _oMountingResetTaps = hasMountingResetTaps() ? mountingResetTaps() : null;
    _o.setMountingResetTaps(_oMountingResetTaps);
    Integer _oNumberTrackersOverThreshold = hasNumberTrackersOverThreshold() ? numberTrackersOverThreshold() : null;
    _o.setNumberTrackersOverThreshold(_oNumberTrackersOverThreshold);
    Integer _oYawResetBoneId = hasYawResetBoneId() ? yawResetBoneId() : null;
    _o.setYawResetBoneId(_oYawResetBoneId);
    Integer _oFullResetBoneId = hasFullResetBoneId() ? fullResetBoneId() : null;
    _o.setFullResetBoneId(_oFullResetBoneId);
    Integer _oMountingResetBoneId = hasMountingResetBoneId() ? mountingResetBoneId() : null;
    _o.setMountingResetBoneId(_oMountingResetBoneId);
  }
  public static int pack(FlatBufferBuilder builder, TapDetectionSettingsResponseT _o) {
    if (_o == null) return 0;
    return createTapDetectionSettingsResponse(
      builder,
      _o.getFullResetDelay(),
      _o.getFullResetEnabled(),
      _o.getFullResetTaps(),
      _o.getYawResetDelay(),
      _o.getYawResetEnabled(),
      _o.getYawResetTaps(),
      _o.getMountingResetDelay(),
      _o.getMountingResetEnabled(),
      _o.getMountingResetTaps(),
      _o.getNumberTrackersOverThreshold(),
      _o.getYawResetBoneId(),
      _o.getFullResetBoneId(),
      _o.getMountingResetBoneId());
  }
}

