// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class TimeoutSettingsT {
  private float duration;

  public float getDuration() { return duration; }

  public void setDuration(float duration) { this.duration = duration; }


  public TimeoutSettingsT() {
    this.duration = 0.0f;
  }
}

