// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class TrackingChecklistTrackerErrorT {
  private int[] trackersId;

  public int[] getTrackersId() { return trackersId; }

  public void setTrackersId(int[] trackersId) { this.trackersId = trackersId; }


  public TrackingChecklistTrackerErrorT() {
    this.trackersId = null;
  }
}

