// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TrackingChecklistUnassignedHMD extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static TrackingChecklistUnassignedHMD getRootAsTrackingChecklistUnassignedHMD(ByteBuffer _bb) { return getRootAsTrackingChecklistUnassignedHMD(_bb, new TrackingChecklistUnassignedHMD()); }
  public static TrackingChecklistUnassignedHMD getRootAsTrackingChecklistUnassignedHMD(ByteBuffer _bb, TrackingChecklistUnassignedHMD obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TrackingChecklistUnassignedHMD __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.datatypes.TrackerId trackerId() { return trackerId(new solarxr_protocol.datatypes.TrackerId()); }
  public solarxr_protocol.datatypes.TrackerId trackerId(solarxr_protocol.datatypes.TrackerId obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createTrackingChecklistUnassignedHMD(FlatBufferBuilder builder,
      int trackerIdOffset) {
    builder.startTable(1);
    TrackingChecklistUnassignedHMD.addTrackerId(builder, trackerIdOffset);
    return TrackingChecklistUnassignedHMD.endTrackingChecklistUnassignedHMD(builder);
  }

  public static void startTrackingChecklistUnassignedHMD(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTrackerId(FlatBufferBuilder builder, int trackerIdOffset) { builder.addOffset(0, trackerIdOffset, 0); }
  public static int endTrackingChecklistUnassignedHMD(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TrackingChecklistUnassignedHMD get(int j) { return get(new TrackingChecklistUnassignedHMD(), j); }
    public TrackingChecklistUnassignedHMD get(TrackingChecklistUnassignedHMD obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public TrackingChecklistUnassignedHMDT unpack() {
    TrackingChecklistUnassignedHMDT _o = new TrackingChecklistUnassignedHMDT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(TrackingChecklistUnassignedHMDT _o) {
    if (trackerId() != null) _o.setTrackerId(trackerId().unpack());
    else _o.setTrackerId(null);
  }
  public static int pack(FlatBufferBuilder builder, TrackingChecklistUnassignedHMDT _o) {
    if (_o == null) return 0;
    int _trackerId = _o.getTrackerId() == null ? 0 : solarxr_protocol.datatypes.TrackerId.pack(builder, _o.getTrackerId());
    return createTrackingChecklistUnassignedHMD(
      builder,
      _trackerId);
  }
}

