// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class TrackingChecklistSteamVRDisconnectedT {
  private String bridgeSettingsName;

  public String getBridgeSettingsName() { return bridgeSettingsName; }

  public void setBridgeSettingsName(String bridgeSettingsName) { this.bridgeSettingsName = bridgeSettingsName; }


  public TrackingChecklistSteamVRDisconnectedT() {
    this.bridgeSettingsName = null;
  }
}

