// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class TrackerProvisioningStateT {
  private String port;
  private String macAddress;
  private int status;

  public String getPort() { return port; }

  public void setPort(String port) { this.port = port; }

  public String getMacAddress() { return macAddress; }

  public void setMacAddress(String macAddress) { this.macAddress = macAddress; }

  public int getStatus() { return status; }

  public void setStatus(int status) { this.status = status; }


  public TrackerProvisioningStateT() {
    this.port = null;
    this.macAddress = null;
    this.status = 0;
  }
}

