// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Trackers that need a reset
 */
@SuppressWarnings("unused")
public final class TrackingChecklistTrackerReset extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static TrackingChecklistTrackerReset getRootAsTrackingChecklistTrackerReset(ByteBuffer _bb) { return getRootAsTrackingChecklistTrackerReset(_bb, new TrackingChecklistTrackerReset()); }
  public static TrackingChecklistTrackerReset getRootAsTrackingChecklistTrackerReset(ByteBuffer _bb, TrackingChecklistTrackerReset obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TrackingChecklistTrackerReset __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int trackersId(int j) { int o = __offset(4); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int trackersIdLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector trackersIdVector() { return trackersIdVector(new ShortVector()); }
  public ShortVector trackersIdVector(ShortVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer trackersIdAsByteBuffer() { return __vector_as_bytebuffer(4, 2); }
  public ByteBuffer trackersIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 2); }

  public static int createTrackingChecklistTrackerReset(FlatBufferBuilder builder,
      int trackersIdOffset) {
    builder.startTable(1);
    TrackingChecklistTrackerReset.addTrackersId(builder, trackersIdOffset);
    return TrackingChecklistTrackerReset.endTrackingChecklistTrackerReset(builder);
  }

  public static void startTrackingChecklistTrackerReset(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTrackersId(FlatBufferBuilder builder, int trackersIdOffset) { builder.addOffset(0, trackersIdOffset, 0); }
  public static int createTrackersIdVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startTrackersIdVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static int endTrackingChecklistTrackerReset(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TrackingChecklistTrackerReset get(int j) { return get(new TrackingChecklistTrackerReset(), j); }
    public TrackingChecklistTrackerReset get(TrackingChecklistTrackerReset obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public TrackingChecklistTrackerResetT unpack() {
    TrackingChecklistTrackerResetT _o = new TrackingChecklistTrackerResetT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(TrackingChecklistTrackerResetT _o) {
    int[] _oTrackersId = new int[trackersIdLength()];
    for (int _j = 0; _j < trackersIdLength(); ++_j) {_oTrackersId[_j] = trackersId(_j);}
    _o.setTrackersId(_oTrackersId);
  }
  public static int pack(FlatBufferBuilder builder, TrackingChecklistTrackerResetT _o) {
    if (_o == null) return 0;
    int _trackersId = 0;
    if (_o.getTrackersId() != null) {
      _trackersId = createTrackersIdVector(builder, _o.getTrackersId());
    }
    return createTrackingChecklistTrackerReset(
      builder,
      _trackersId);
  }
}

