// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserHeightSettingsResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static UserHeightSettingsResponse getRootAsUserHeightSettingsResponse(ByteBuffer _bb) { return getRootAsUserHeightSettingsResponse(_bb, new UserHeightSettingsResponse()); }
  public static UserHeightSettingsResponse getRootAsUserHeightSettingsResponse(ByteBuffer _bb, UserHeightSettingsResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UserHeightSettingsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean hasHmdHeight() { return 0 != __offset(4); }
  public float hmdHeight() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0f; }
  public boolean hasFloorHeight() { return 0 != __offset(6); }
  public float floorHeight() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0f; }

  public static int createUserHeightSettingsResponse(FlatBufferBuilder builder,
      float hmdHeight,
      float floorHeight) {
    builder.startTable(2);
    UserHeightSettingsResponse.addFloorHeight(builder, floorHeight);
    UserHeightSettingsResponse.addHmdHeight(builder, hmdHeight);
    return UserHeightSettingsResponse.endUserHeightSettingsResponse(builder);
  }

  public static void startUserHeightSettingsResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addHmdHeight(FlatBufferBuilder builder, float hmdHeight) { builder.addFloat(0, hmdHeight, 0f); }
  public static void addFloorHeight(FlatBufferBuilder builder, float floorHeight) { builder.addFloat(1, floorHeight, 0f); }
  public static int endUserHeightSettingsResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UserHeightSettingsResponse get(int j) { return get(new UserHeightSettingsResponse(), j); }
    public UserHeightSettingsResponse get(UserHeightSettingsResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public UserHeightSettingsResponseT unpack() {
    UserHeightSettingsResponseT _o = new UserHeightSettingsResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(UserHeightSettingsResponseT _o) {
    Float _oHmdHeight = hasHmdHeight() ? hmdHeight() : null;
    _o.setHmdHeight(_oHmdHeight);
    Float _oFloorHeight = hasFloorHeight() ? floorHeight() : null;
    _o.setFloorHeight(_oFloorHeight);
  }
  public static int pack(FlatBufferBuilder builder, UserHeightSettingsResponseT _o) {
    if (_o == null) return 0;
    return createUserHeightSettingsResponse(
      builder,
      _o.getHmdHeight(),
      _o.getFloorHeight());
  }
}

