// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class VideoTrackerCalibrationStatus {
  private VideoTrackerCalibrationStatus() { }
  public static final int CALIBRATE_CAMERA = 0;
  public static final int CAPTURE_FORWARD_POSE = 1;
  public static final int CAPTURE_BENT_OVER_POSE = 2;
  public static final int CALIBRATE_TRACKERS = 3;
  public static final int CALIBRATE_SKELETON_OFFSETS = 4;
  public static final int DONE = 100;
}

