// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class VRCOSCSettingsT {
  private boolean enabled;
  private int portIn;
  private int portOut;
  private solarxr_protocol.datatypes.Ipv4AddressT address;
  private solarxr_protocol.rpc.OSCTrackersSettingT trackers;

  public boolean getEnabled() { return enabled; }

  public void setEnabled(boolean enabled) { this.enabled = enabled; }

  public int getPortIn() { return portIn; }

  public void setPortIn(int portIn) { this.portIn = portIn; }

  public int getPortOut() { return portOut; }

  public void setPortOut(int portOut) { this.portOut = portOut; }

  public solarxr_protocol.datatypes.Ipv4AddressT getAddress() { return address; }

  public void setAddress(solarxr_protocol.datatypes.Ipv4AddressT address) { this.address = address; }

  public solarxr_protocol.rpc.OSCTrackersSettingT getTrackers() { return trackers; }

  public void setTrackers(solarxr_protocol.rpc.OSCTrackersSettingT trackers) { this.trackers = trackers; }


  public VRCOSCSettingsT() {
    this.enabled = false;
    this.portIn = 0;
    this.portOut = 0;
    this.address = new solarxr_protocol.datatypes.Ipv4AddressT();
    this.trackers = null;
  }
}

