// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VRCOSCSettings extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static VRCOSCSettings getRootAsVRCOSCSettings(ByteBuffer _bb) { return getRootAsVRCOSCSettings(_bb, new VRCOSCSettings()); }
  public static VRCOSCSettings getRootAsVRCOSCSettings(ByteBuffer _bb, VRCOSCSettings obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VRCOSCSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enabled() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int portIn() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int portOut() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public solarxr_protocol.datatypes.Ipv4Address address() { return address(new solarxr_protocol.datatypes.Ipv4Address()); }
  public solarxr_protocol.datatypes.Ipv4Address address(solarxr_protocol.datatypes.Ipv4Address obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public solarxr_protocol.rpc.OSCTrackersSetting trackers() { return trackers(new solarxr_protocol.rpc.OSCTrackersSetting()); }
  public solarxr_protocol.rpc.OSCTrackersSetting trackers(solarxr_protocol.rpc.OSCTrackersSetting obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static void startVRCOSCSettings(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addEnabled(FlatBufferBuilder builder, boolean enabled) { builder.addBoolean(0, enabled, false); }
  public static void addPortIn(FlatBufferBuilder builder, int portIn) { builder.addShort(1, (short) portIn, (short) 0); }
  public static void addPortOut(FlatBufferBuilder builder, int portOut) { builder.addShort(2, (short) portOut, (short) 0); }
  public static void addAddress(FlatBufferBuilder builder, int addressOffset) { builder.addStruct(3, addressOffset, 0); }
  public static void addTrackers(FlatBufferBuilder builder, int trackersOffset) { builder.addOffset(4, trackersOffset, 0); }
  public static int endVRCOSCSettings(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VRCOSCSettings get(int j) { return get(new VRCOSCSettings(), j); }
    public VRCOSCSettings get(VRCOSCSettings obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public VRCOSCSettingsT unpack() {
    VRCOSCSettingsT _o = new VRCOSCSettingsT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(VRCOSCSettingsT _o) {
    boolean _oEnabled = enabled();
    _o.setEnabled(_oEnabled);
    int _oPortIn = portIn();
    _o.setPortIn(_oPortIn);
    int _oPortOut = portOut();
    _o.setPortOut(_oPortOut);
    if (address() != null) address().unpackTo(_o.getAddress());
    else _o.setAddress(null);
    if (trackers() != null) _o.setTrackers(trackers().unpack());
    else _o.setTrackers(null);
  }
  public static int pack(FlatBufferBuilder builder, VRCOSCSettingsT _o) {
    if (_o == null) return 0;
    int _trackers = _o.getTrackers() == null ? 0 : solarxr_protocol.rpc.OSCTrackersSetting.pack(builder, _o.getTrackers());
    startVRCOSCSettings(builder);
    addEnabled(builder, _o.getEnabled());
    addPortIn(builder, _o.getPortIn());
    addPortOut(builder, _o.getPortOut());
    addAddress(builder, solarxr_protocol.datatypes.Ipv4Address.pack(builder, _o.getAddress()));
    addTrackers(builder, _trackers);
    return endVRCOSCSettings(builder);
  }
}

