// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.firmware.commands;

import com.google.flatbuffers.FlatBufferBuilder;

public class CommandMessageUnion {
  private byte type;
  private Object value;

  public byte getType() { return type; }

  public void setType(byte type) { this.type = type; }

  public Object getValue() { return value; }

  public void setValue(Object value) { this.value = value; }

  public CommandMessageUnion() {
    this.type = CommandMessage.NONE;
    this.value = null;
  }

  public solarxr_protocol.firmware.commands.TapResponseT asTapResponse() { return (solarxr_protocol.firmware.commands.TapResponseT) value; }

  public static int pack(FlatBufferBuilder builder, CommandMessageUnion _o) {
    switch (_o.type) {
      case CommandMessage.TapResponse: return solarxr_protocol.firmware.commands.TapResponse.pack(builder, _o.asTapResponse());
      default: return 0;
    }
  }
}

