// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Bone, BoneT } from '../../solarxr-protocol/data-feed/bone.js';
import { DeviceData, DeviceDataT } from '../../solarxr-protocol/data-feed/device-data/device-data.js';
import { DongleData, DongleDataT } from '../../solarxr-protocol/data-feed/dongle-data/dongle-data.js';
import { ServerGuards, ServerGuardsT } from '../../solarxr-protocol/data-feed/server/server-guards.js';


/**
 * All of the data components related to a single data feed. A data feed is comprised
 * of device data, and tracker data.
 *
 * A data feed might send data only when it changes/updates, and we should make no
 * assumptions that the data is actually delivered. If you want to guarantee
 * delivery and avoid dropped observations of data (such as a user-initiated
 * button press), it is better to use the RPC system.
 */
export class DataFeedUpdate implements flatbuffers.IUnpackableObject<DataFeedUpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DataFeedUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDataFeedUpdate(bb:flatbuffers.ByteBuffer, obj?:DataFeedUpdate):DataFeedUpdate {
  return (obj || new DataFeedUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDataFeedUpdate(bb:flatbuffers.ByteBuffer, obj?:DataFeedUpdate):DataFeedUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DataFeedUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

devices(index: number, obj?:DeviceData):DeviceData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DeviceData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

devicesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * This must represent a set, where there is no more than one bone for a `BodyPart`.
 */
bones(index: number, obj?:Bone):Bone|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Bone()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

bonesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * gives the index of the datafeed config that initiated the update
 */
index():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

serverGuards(obj?:ServerGuards):ServerGuards|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ServerGuards()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * List of HID dongles connected to the server
 */
dongles(index: number, obj?:DongleData):DongleData|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new DongleData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

donglesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDataFeedUpdate(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addDevices(builder:flatbuffers.Builder, devicesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, devicesOffset, 0);
}

static createDevicesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDevicesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBones(builder:flatbuffers.Builder, bonesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bonesOffset, 0);
}

static createBonesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBonesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt8(2, index, 0);
}

static addServerGuards(builder:flatbuffers.Builder, serverGuardsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, serverGuardsOffset, 0);
}

static addDongles(builder:flatbuffers.Builder, donglesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, donglesOffset, 0);
}

static createDonglesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDonglesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDataFeedUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): DataFeedUpdateT {
  return new DataFeedUpdateT(
    this.bb!.createObjList<DeviceData, DeviceDataT>(this.devices.bind(this), this.devicesLength()),
    this.bb!.createObjList<Bone, BoneT>(this.bones.bind(this), this.bonesLength()),
    this.index(),
    (this.serverGuards() !== null ? this.serverGuards()!.unpack() : null),
    this.bb!.createObjList<DongleData, DongleDataT>(this.dongles.bind(this), this.donglesLength())
  );
}


unpackTo(_o: DataFeedUpdateT): void {
  _o.devices = this.bb!.createObjList<DeviceData, DeviceDataT>(this.devices.bind(this), this.devicesLength());
  _o.bones = this.bb!.createObjList<Bone, BoneT>(this.bones.bind(this), this.bonesLength());
  _o.index = this.index();
  _o.serverGuards = (this.serverGuards() !== null ? this.serverGuards()!.unpack() : null);
  _o.dongles = this.bb!.createObjList<DongleData, DongleDataT>(this.dongles.bind(this), this.donglesLength());
}
}

export class DataFeedUpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public devices: (DeviceDataT)[] = [],
  public bones: (BoneT)[] = [],
  public index: number = 0,
  public serverGuards: ServerGuardsT|null = null,
  public dongles: (DongleDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const devices = DataFeedUpdate.createDevicesVector(builder, builder.createObjectOffsetList(this.devices));
  const bones = DataFeedUpdate.createBonesVector(builder, builder.createObjectOffsetList(this.bones));
  const serverGuards = (this.serverGuards !== null ? this.serverGuards!.pack(builder) : 0);
  const dongles = DataFeedUpdate.createDonglesVector(builder, builder.createObjectOffsetList(this.dongles));

  DataFeedUpdate.startDataFeedUpdate(builder);
  DataFeedUpdate.addDevices(builder, devices);
  DataFeedUpdate.addBones(builder, bones);
  DataFeedUpdate.addIndex(builder, this.index);
  DataFeedUpdate.addServerGuards(builder, serverGuards);
  DataFeedUpdate.addDongles(builder, dongles);

  return DataFeedUpdate.endDataFeedUpdate(builder);
}
}
