// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Different parts of the body. Roughly maps to each possible bone in the skeleton.
 * These are *NOT* the trackers.
 */
export enum BodyPart {
  NONE = 0,
  HEAD = 1,
  NECK = 2,
  UPPER_CHEST = 3,
  CHEST = 4,
  WAIST = 5,
  HIP = 6,
  LEFT_UPPER_LEG = 7,
  RIGHT_UPPER_LEG = 8,
  LEFT_LOWER_LEG = 9,
  RIGHT_LOWER_LEG = 10,
  LEFT_FOOT = 11,
  RIGHT_FOOT = 12,
  LEFT_LOWER_ARM = 13,
  RIGHT_LOWER_ARM = 14,
  LEFT_UPPER_ARM = 15,
  RIGHT_UPPER_ARM = 16,
  LEFT_HAND = 17,
  RIGHT_HAND = 18,
  LEFT_SHOULDER = 19,
  RIGHT_SHOULDER = 20
}
