// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Used for filtering tracker rotations in software
 */
export enum FilteringType {
  NONE = 0,
  SMOOTHING = 1,
  PREDICTION = 2
}
