// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TrackerStatus {
  NONE = 0,
  DISCONNECTED = 1,
  OK = 2,
  BUSY = 3,
  ERROR = 4,
  OCCLUDED = 5,
  TIMED_OUT = 6
}
