// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { RegistrationStatus } from '../../solarxr-protocol/driver-protocol/registration-status.js';


/**
 * Response to a RegisterDriver request. The server may send it later if it wishes to
 * stop communication with your driver for whatever reason, e.g. the user has disabled the driver in settings.
 */
export class DriverRegistrationResponse implements flatbuffers.IUnpackableObject<DriverRegistrationResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DriverRegistrationResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDriverRegistrationResponse(bb:flatbuffers.ByteBuffer, obj?:DriverRegistrationResponse):DriverRegistrationResponse {
  return (obj || new DriverRegistrationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDriverRegistrationResponse(bb:flatbuffers.ByteBuffer, obj?:DriverRegistrationResponse):DriverRegistrationResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DriverRegistrationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():RegistrationStatus {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RegistrationStatus.ACCEPTED;
}

static startDriverRegistrationResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatus(builder:flatbuffers.Builder, status:RegistrationStatus) {
  builder.addFieldInt8(0, status, RegistrationStatus.ACCEPTED);
}

static endDriverRegistrationResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDriverRegistrationResponse(builder:flatbuffers.Builder, status:RegistrationStatus):flatbuffers.Offset {
  DriverRegistrationResponse.startDriverRegistrationResponse(builder);
  DriverRegistrationResponse.addStatus(builder, status);
  return DriverRegistrationResponse.endDriverRegistrationResponse(builder);
}

unpack(): DriverRegistrationResponseT {
  return new DriverRegistrationResponseT(
    this.status()
  );
}


unpackTo(_o: DriverRegistrationResponseT): void {
  _o.status = this.status();
}
}

export class DriverRegistrationResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public status: RegistrationStatus = RegistrationStatus.ACCEPTED
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return DriverRegistrationResponse.createDriverRegistrationResponse(builder,
    this.status
  );
}
}
