// automatically generated by the FlatBuffers compiler, do not modify

import { AddTrackerRequest, AddTrackerRequestT } from '../../solarxr-protocol/driver-protocol/add-tracker-request.js';
import { AddTrackerResponse, AddTrackerResponseT } from '../../solarxr-protocol/driver-protocol/add-tracker-response.js';
import { BoneBatteryUpdate, BoneBatteryUpdateT } from '../../solarxr-protocol/driver-protocol/bone-battery-update.js';
import { HandshakeAvailable, HandshakeAvailableT } from '../../solarxr-protocol/driver-protocol/handshake-available.js';
import { HandshakeRequest, HandshakeRequestT } from '../../solarxr-protocol/driver-protocol/handshake-request.js';
import { HandshakeResponse, HandshakeResponseT } from '../../solarxr-protocol/driver-protocol/handshake-response.js';
import { SkeletonUpdate, SkeletonUpdateT } from '../../solarxr-protocol/driver-protocol/skeleton-update.js';
import { UpdateTrackerBattery, UpdateTrackerBatteryT } from '../../solarxr-protocol/driver-protocol/update-tracker-battery.js';
import { UpdateTrackerPosition, UpdateTrackerPositionT } from '../../solarxr-protocol/driver-protocol/update-tracker-position.js';
import { UpdateTrackerStatus, UpdateTrackerStatusT } from '../../solarxr-protocol/driver-protocol/update-tracker-status.js';


export enum DriverMessage {
  NONE = 0,
  HandshakeAvailable = 1,
  HandshakeRequest = 2,
  HandshakeResponse = 3,
  AddTrackerRequest = 4,
  AddTrackerResponse = 5,
  UpdateTrackerStatus = 6,
  UpdateTrackerBattery = 7,
  UpdateTrackerPosition = 8,
  SkeletonUpdate = 9,
  BoneBatteryUpdate = 10
}

export function unionToDriverMessage(
  type: DriverMessage,
  accessor: (obj:AddTrackerRequest|AddTrackerResponse|BoneBatteryUpdate|HandshakeAvailable|HandshakeRequest|HandshakeResponse|SkeletonUpdate|UpdateTrackerBattery|UpdateTrackerPosition|UpdateTrackerStatus) => AddTrackerRequest|AddTrackerResponse|BoneBatteryUpdate|HandshakeAvailable|HandshakeRequest|HandshakeResponse|SkeletonUpdate|UpdateTrackerBattery|UpdateTrackerPosition|UpdateTrackerStatus|null
): AddTrackerRequest|AddTrackerResponse|BoneBatteryUpdate|HandshakeAvailable|HandshakeRequest|HandshakeResponse|SkeletonUpdate|UpdateTrackerBattery|UpdateTrackerPosition|UpdateTrackerStatus|null {
  switch(DriverMessage[type]) {
    case 'NONE': return null; 
    case 'HandshakeAvailable': return accessor(new HandshakeAvailable())! as HandshakeAvailable;
    case 'HandshakeRequest': return accessor(new HandshakeRequest())! as HandshakeRequest;
    case 'HandshakeResponse': return accessor(new HandshakeResponse())! as HandshakeResponse;
    case 'AddTrackerRequest': return accessor(new AddTrackerRequest())! as AddTrackerRequest;
    case 'AddTrackerResponse': return accessor(new AddTrackerResponse())! as AddTrackerResponse;
    case 'UpdateTrackerStatus': return accessor(new UpdateTrackerStatus())! as UpdateTrackerStatus;
    case 'UpdateTrackerBattery': return accessor(new UpdateTrackerBattery())! as UpdateTrackerBattery;
    case 'UpdateTrackerPosition': return accessor(new UpdateTrackerPosition())! as UpdateTrackerPosition;
    case 'SkeletonUpdate': return accessor(new SkeletonUpdate())! as SkeletonUpdate;
    case 'BoneBatteryUpdate': return accessor(new BoneBatteryUpdate())! as BoneBatteryUpdate;
    default: return null;
  }
}

export function unionListToDriverMessage(
  type: DriverMessage, 
  accessor: (index: number, obj:AddTrackerRequest|AddTrackerResponse|BoneBatteryUpdate|HandshakeAvailable|HandshakeRequest|HandshakeResponse|SkeletonUpdate|UpdateTrackerBattery|UpdateTrackerPosition|UpdateTrackerStatus) => AddTrackerRequest|AddTrackerResponse|BoneBatteryUpdate|HandshakeAvailable|HandshakeRequest|HandshakeResponse|SkeletonUpdate|UpdateTrackerBattery|UpdateTrackerPosition|UpdateTrackerStatus|null, 
  index: number
): AddTrackerRequest|AddTrackerResponse|BoneBatteryUpdate|HandshakeAvailable|HandshakeRequest|HandshakeResponse|SkeletonUpdate|UpdateTrackerBattery|UpdateTrackerPosition|UpdateTrackerStatus|null {
  switch(DriverMessage[type]) {
    case 'NONE': return null; 
    case 'HandshakeAvailable': return accessor(index, new HandshakeAvailable())! as HandshakeAvailable;
    case 'HandshakeRequest': return accessor(index, new HandshakeRequest())! as HandshakeRequest;
    case 'HandshakeResponse': return accessor(index, new HandshakeResponse())! as HandshakeResponse;
    case 'AddTrackerRequest': return accessor(index, new AddTrackerRequest())! as AddTrackerRequest;
    case 'AddTrackerResponse': return accessor(index, new AddTrackerResponse())! as AddTrackerResponse;
    case 'UpdateTrackerStatus': return accessor(index, new UpdateTrackerStatus())! as UpdateTrackerStatus;
    case 'UpdateTrackerBattery': return accessor(index, new UpdateTrackerBattery())! as UpdateTrackerBattery;
    case 'UpdateTrackerPosition': return accessor(index, new UpdateTrackerPosition())! as UpdateTrackerPosition;
    case 'SkeletonUpdate': return accessor(index, new SkeletonUpdate())! as SkeletonUpdate;
    case 'BoneBatteryUpdate': return accessor(index, new BoneBatteryUpdate())! as BoneBatteryUpdate;
    default: return null;
  }
}
