// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { AddTrackerRequest, AddTrackerRequestT } from '../../solarxr-protocol/driver-protocol/add-tracker-request.js';
import { AddTrackerResponse, AddTrackerResponseT } from '../../solarxr-protocol/driver-protocol/add-tracker-response.js';
import { BoneBatteryUpdate, BoneBatteryUpdateT } from '../../solarxr-protocol/driver-protocol/bone-battery-update.js';
import { DriverMessage, unionToDriverMessage, unionListToDriverMessage } from '../../solarxr-protocol/driver-protocol/driver-message.js';
import { HandshakeAvailable, HandshakeAvailableT } from '../../solarxr-protocol/driver-protocol/handshake-available.js';
import { HandshakeRequest, HandshakeRequestT } from '../../solarxr-protocol/driver-protocol/handshake-request.js';
import { HandshakeResponse, HandshakeResponseT } from '../../solarxr-protocol/driver-protocol/handshake-response.js';
import { SkeletonUpdate, SkeletonUpdateT } from '../../solarxr-protocol/driver-protocol/skeleton-update.js';
import { UpdateTrackerBattery, UpdateTrackerBatteryT } from '../../solarxr-protocol/driver-protocol/update-tracker-battery.js';
import { UpdateTrackerPosition, UpdateTrackerPositionT } from '../../solarxr-protocol/driver-protocol/update-tracker-position.js';
import { UpdateTrackerStatus, UpdateTrackerStatusT } from '../../solarxr-protocol/driver-protocol/update-tracker-status.js';


export class DriverMessageHeader implements flatbuffers.IUnpackableObject<DriverMessageHeaderT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DriverMessageHeader {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDriverMessageHeader(bb:flatbuffers.ByteBuffer, obj?:DriverMessageHeader):DriverMessageHeader {
  return (obj || new DriverMessageHeader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDriverMessageHeader(bb:flatbuffers.ByteBuffer, obj?:DriverMessageHeader):DriverMessageHeader {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DriverMessageHeader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Set by whoever originates this message, so a future reply can reference it.
 * Absent for one-way notifications that expect no reply.
 */
txId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * Set only on a reply, the tx_id of the request this answers. Never set together with tx_id.
 */
replyTo():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

messageType():DriverMessage {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DriverMessage.NONE;
}

message<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startDriverMessageHeader(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTxId(builder:flatbuffers.Builder, txId:number) {
  builder.addFieldInt32(0, txId, 0);
}

static addReplyTo(builder:flatbuffers.Builder, replyTo:number) {
  builder.addFieldInt32(1, replyTo, 0);
}

static addMessageType(builder:flatbuffers.Builder, messageType:DriverMessage) {
  builder.addFieldInt8(2, messageType, DriverMessage.NONE);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, messageOffset, 0);
}

static endDriverMessageHeader(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDriverMessageHeader(builder:flatbuffers.Builder, txId:number, replyTo:number, messageType:DriverMessage, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  DriverMessageHeader.startDriverMessageHeader(builder);
  DriverMessageHeader.addTxId(builder, txId);
  DriverMessageHeader.addReplyTo(builder, replyTo);
  DriverMessageHeader.addMessageType(builder, messageType);
  DriverMessageHeader.addMessage(builder, messageOffset);
  return DriverMessageHeader.endDriverMessageHeader(builder);
}

unpack(): DriverMessageHeaderT {
  return new DriverMessageHeaderT(
    this.txId(),
    this.replyTo(),
    this.messageType(),
    (() => {
      const temp = unionToDriverMessage(this.messageType(), this.message.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: DriverMessageHeaderT): void {
  _o.txId = this.txId();
  _o.replyTo = this.replyTo();
  _o.messageType = this.messageType();
  _o.message = (() => {
      const temp = unionToDriverMessage(this.messageType(), this.message.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class DriverMessageHeaderT implements flatbuffers.IGeneratedObject {
constructor(
  public txId: number = 0,
  public replyTo: number = 0,
  public messageType: DriverMessage = DriverMessage.NONE,
  public message: AddTrackerRequestT|AddTrackerResponseT|BoneBatteryUpdateT|HandshakeAvailableT|HandshakeRequestT|HandshakeResponseT|SkeletonUpdateT|UpdateTrackerBatteryT|UpdateTrackerPositionT|UpdateTrackerStatusT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = builder.createObjectOffset(this.message);

  return DriverMessageHeader.createDriverMessageHeader(builder,
    this.txId,
    this.replyTo,
    this.messageType,
    message
  );
}
}
