// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { TrackerStatus } from '../../solarxr-protocol/datatypes/tracker-status.js';


export class InboundTrackerStatusNotification implements flatbuffers.IUnpackableObject<InboundTrackerStatusNotificationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InboundTrackerStatusNotification {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInboundTrackerStatusNotification(bb:flatbuffers.ByteBuffer, obj?:InboundTrackerStatusNotification):InboundTrackerStatusNotification {
  return (obj || new InboundTrackerStatusNotification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInboundTrackerStatusNotification(bb:flatbuffers.ByteBuffer, obj?:InboundTrackerStatusNotification):InboundTrackerStatusNotification {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InboundTrackerStatusNotification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

trackerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

status():TrackerStatus {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TrackerStatus.NONE;
}

static startInboundTrackerStatusNotification(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTrackerId(builder:flatbuffers.Builder, trackerId:number) {
  builder.addFieldInt16(0, trackerId, 0);
}

static addStatus(builder:flatbuffers.Builder, status:TrackerStatus) {
  builder.addFieldInt8(1, status, TrackerStatus.NONE);
}

static endInboundTrackerStatusNotification(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInboundTrackerStatusNotification(builder:flatbuffers.Builder, trackerId:number, status:TrackerStatus):flatbuffers.Offset {
  InboundTrackerStatusNotification.startInboundTrackerStatusNotification(builder);
  InboundTrackerStatusNotification.addTrackerId(builder, trackerId);
  InboundTrackerStatusNotification.addStatus(builder, status);
  return InboundTrackerStatusNotification.endInboundTrackerStatusNotification(builder);
}

unpack(): InboundTrackerStatusNotificationT {
  return new InboundTrackerStatusNotificationT(
    this.trackerId(),
    this.status()
  );
}


unpackTo(_o: InboundTrackerStatusNotificationT): void {
  _o.trackerId = this.trackerId();
  _o.status = this.status();
}
}

export class InboundTrackerStatusNotificationT implements flatbuffers.IGeneratedObject {
constructor(
  public trackerId: number = 0,
  public status: TrackerStatus = TrackerStatus.NONE
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return InboundTrackerStatusNotification.createInboundTrackerStatusNotification(builder,
    this.trackerId,
    this.status
  );
}
}
