// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class DeviceFeatureInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):DeviceFeatureInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDeviceFeatureInfo(bb:flatbuffers.ByteBuffer, obj?:DeviceFeatureInfo):DeviceFeatureInfo {
  return (obj || new DeviceFeatureInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDeviceFeatureInfo(bb:flatbuffers.ByteBuffer, obj?:DeviceFeatureInfo):DeviceFeatureInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DeviceFeatureInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDeviceFeatureInfo(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDeviceFeatureInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDeviceFeatureInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  DeviceFeatureInfo.startDeviceFeatureInfo(builder);
  return DeviceFeatureInfo.endDeviceFeatureInfo(builder);
}

unpack(): DeviceFeatureInfoT {
  return new DeviceFeatureInfoT();
}


unpackTo(_o: DeviceFeatureInfoT): void {}
}

export class DeviceFeatureInfoT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return DeviceFeatureInfo.createDeviceFeatureInfo(builder);
}
}
