// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class BoneDefinition implements flatbuffers.IUnpackableObject<BoneDefinitionT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BoneDefinition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBoneDefinition(bb:flatbuffers.ByteBuffer, obj?:BoneDefinition):BoneDefinition {
  return (obj || new BoneDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBoneDefinition(bb:flatbuffers.ByteBuffer, obj?:BoneDefinition):BoneDefinition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BoneDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The parent's ID, or 0 if this bone has no parent (a root).
 */
parent():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startBoneDefinition(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt16(0, id, 0);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, displayNameOffset, 0);
}

static addParent(builder:flatbuffers.Builder, parent:number) {
  builder.addFieldInt16(3, parent, 0);
}

static endBoneDefinition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // key
  return offset;
}

static createBoneDefinition(builder:flatbuffers.Builder, id:number, keyOffset:flatbuffers.Offset, displayNameOffset:flatbuffers.Offset, parent:number):flatbuffers.Offset {
  BoneDefinition.startBoneDefinition(builder);
  BoneDefinition.addId(builder, id);
  BoneDefinition.addKey(builder, keyOffset);
  BoneDefinition.addDisplayName(builder, displayNameOffset);
  BoneDefinition.addParent(builder, parent);
  return BoneDefinition.endBoneDefinition(builder);
}

unpack(): BoneDefinitionT {
  return new BoneDefinitionT(
    this.id(),
    this.key(),
    this.displayName(),
    this.parent()
  );
}


unpackTo(_o: BoneDefinitionT): void {
  _o.id = this.id();
  _o.key = this.key();
  _o.displayName = this.displayName();
  _o.parent = this.parent();
}
}

export class BoneDefinitionT implements flatbuffers.IGeneratedObject {
constructor(
  public id: number = 0,
  public key: string|Uint8Array|null = null,
  public displayName: string|Uint8Array|null = null,
  public parent: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? builder.createString(this.key!) : 0);
  const displayName = (this.displayName !== null ? builder.createString(this.displayName!) : 0);

  return BoneDefinition.createBoneDefinition(builder,
    this.id,
    key,
    displayName,
    this.parent
  );
}
}
