/// This file contains datatypes that are shared across several places in SolarXR
/// If a datatype is only used in one place, it should be placed there.

namespace solarxr_protocol.datatypes;

/// General purpose logging datatype
table LogData {
    message: string;
    data: [uint8];
}

/// A list of error codes for error conditions on the device
enum FirmwareErrorCode: uint8 {
    Other = 0,
    Disconnected,
    Occluded,
    ImuError,
}

enum TrackerStatus: uint8 {
    NONE = 0,
    DISCONNECTED = 1,
    OK = 2,
    BUSY = 3,
    ERROR = 4,
    OCCLUDED = 5,
    TIMED_OUT = 6,
    SLEEPING = 7,
}

enum MagnetometerStatus: uint8 {
    NOT_SUPPORTED = 0,
    DISABLED = 1,
    ENABLED = 2,
}

enum MountingMethod: uint8 {
	MANUAL = 0,
	POSE = 1,
}

enum DeviceOrigin: uint8 {
    NONE = 0,
    DRIVER = 1,
    UDP = 2,
    HID = 3,
    VRC = 4,
    VMC = 5,
}
