// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Request to add a tracker. The server will reply with an AddTrackerResponse.
 */
@SuppressWarnings("unused")
public final class AddTrackerRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static AddTrackerRequest getRootAsAddTrackerRequest(ByteBuffer _bb) { return getRootAsAddTrackerRequest(_bb, new AddTrackerRequest()); }
  public static AddTrackerRequest getRootAsAddTrackerRequest(ByteBuffer _bb, AddTrackerRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AddTrackerRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * A unique identifier, such as a serial number, for the tracker.
   */
  public String hardwareIdentifier() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hardwareIdentifierAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer hardwareIdentifierInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  /**
   * A human-friendly name to display as the name of the tracker.
   */
  public String displayName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer displayNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer displayNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  /**
   * A human-friendly string for the manufacturer of the tracker.
   */
  public String manufacturer() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer manufacturerAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer manufacturerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  /**
   * The body part the tracker should be assigned to by default.
   */
  public int bodyPart() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createAddTrackerRequest(FlatBufferBuilder builder,
      int hardwareIdentifierOffset,
      int displayNameOffset,
      int manufacturerOffset,
      int bodyPart) {
    builder.startTable(4);
    AddTrackerRequest.addManufacturer(builder, manufacturerOffset);
    AddTrackerRequest.addDisplayName(builder, displayNameOffset);
    AddTrackerRequest.addHardwareIdentifier(builder, hardwareIdentifierOffset);
    AddTrackerRequest.addBodyPart(builder, bodyPart);
    return AddTrackerRequest.endAddTrackerRequest(builder);
  }

  public static void startAddTrackerRequest(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addHardwareIdentifier(FlatBufferBuilder builder, int hardwareIdentifierOffset) { builder.addOffset(0, hardwareIdentifierOffset, 0); }
  public static void addDisplayName(FlatBufferBuilder builder, int displayNameOffset) { builder.addOffset(1, displayNameOffset, 0); }
  public static void addManufacturer(FlatBufferBuilder builder, int manufacturerOffset) { builder.addOffset(2, manufacturerOffset, 0); }
  public static void addBodyPart(FlatBufferBuilder builder, int bodyPart) { builder.addByte(3, (byte) bodyPart, (byte) 0); }
  public static int endAddTrackerRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AddTrackerRequest get(int j) { return get(new AddTrackerRequest(), j); }
    public AddTrackerRequest get(AddTrackerRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public AddTrackerRequestT unpack() {
    AddTrackerRequestT _o = new AddTrackerRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(AddTrackerRequestT _o) {
    String _oHardwareIdentifier = hardwareIdentifier();
    _o.setHardwareIdentifier(_oHardwareIdentifier);
    String _oDisplayName = displayName();
    _o.setDisplayName(_oDisplayName);
    String _oManufacturer = manufacturer();
    _o.setManufacturer(_oManufacturer);
    int _oBodyPart = bodyPart();
    _o.setBodyPart(_oBodyPart);
  }
  public static int pack(FlatBufferBuilder builder, AddTrackerRequestT _o) {
    if (_o == null) return 0;
    int _hardwareIdentifier = _o.getHardwareIdentifier() == null ? 0 : builder.createString(_o.getHardwareIdentifier());
    int _displayName = _o.getDisplayName() == null ? 0 : builder.createString(_o.getDisplayName());
    int _manufacturer = _o.getManufacturer() == null ? 0 : builder.createString(_o.getManufacturer());
    return createAddTrackerRequest(
      builder,
      _hardwareIdentifier,
      _displayName,
      _manufacturer,
      _o.getBodyPart());
  }
}

