// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class BoneBatteryUpdateT {
  private int boneId;
  private int batteryLevel;
  private boolean charging;

  public int getBoneId() { return boneId; }

  public void setBoneId(int boneId) { this.boneId = boneId; }

  public int getBatteryLevel() { return batteryLevel; }

  public void setBatteryLevel(int batteryLevel) { this.batteryLevel = batteryLevel; }

  public boolean getCharging() { return charging; }

  public void setCharging(boolean charging) { this.charging = charging; }


  public BoneBatteryUpdateT() {
    this.boneId = 0;
    this.batteryLevel = 0;
    this.charging = false;
  }
}

