// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * The battery information for the tracker associated with this bone has changed. This event will not be sent if the
 * associated tracker does not transmit battery information.
 */
@SuppressWarnings("unused")
public final class BoneBatteryUpdate extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static BoneBatteryUpdate getRootAsBoneBatteryUpdate(ByteBuffer _bb) { return getRootAsBoneBatteryUpdate(_bb, new BoneBatteryUpdate()); }
  public static BoneBatteryUpdate getRootAsBoneBatteryUpdate(ByteBuffer _bb, BoneBatteryUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BoneBatteryUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int bone() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  /**
   * The current battery level. (0..=100)
   */
  public int batteryLevel() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  /**
   * If the tracker is charging.
   */
  public boolean charging() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createBoneBatteryUpdate(FlatBufferBuilder builder,
      int bone,
      int batteryLevel,
      boolean charging) {
    builder.startTable(3);
    BoneBatteryUpdate.addCharging(builder, charging);
    BoneBatteryUpdate.addBatteryLevel(builder, batteryLevel);
    BoneBatteryUpdate.addBone(builder, bone);
    return BoneBatteryUpdate.endBoneBatteryUpdate(builder);
  }

  public static void startBoneBatteryUpdate(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addBone(FlatBufferBuilder builder, int bone) { builder.addByte(0, (byte) bone, (byte) 0); }
  public static void addBatteryLevel(FlatBufferBuilder builder, int batteryLevel) { builder.addByte(1, (byte) batteryLevel, (byte) 0); }
  public static void addCharging(FlatBufferBuilder builder, boolean charging) { builder.addBoolean(2, charging, false); }
  public static int endBoneBatteryUpdate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BoneBatteryUpdate get(int j) { return get(new BoneBatteryUpdate(), j); }
    public BoneBatteryUpdate get(BoneBatteryUpdate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public BoneBatteryUpdateT unpack() {
    BoneBatteryUpdateT _o = new BoneBatteryUpdateT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(BoneBatteryUpdateT _o) {
    int _oBone = bone();
    _o.setBone(_oBone);
    int _oBatteryLevel = batteryLevel();
    _o.setBatteryLevel(_oBatteryLevel);
    boolean _oCharging = charging();
    _o.setCharging(_oCharging);
  }
  public static int pack(FlatBufferBuilder builder, BoneBatteryUpdateT _o) {
    if (_o == null) return 0;
    return createBoneBatteryUpdate(
      builder,
      _o.getBone(),
      _o.getBatteryLevel(),
      _o.getCharging());
  }
}

