// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

@SuppressWarnings("unused")
public final class HandshakeStatus {
  private HandshakeStatus() { }
  public static final int ACCEPTED = 0;
  public static final int REJECTED_UNNAMED = 1;
  public static final int REJECTED_DUPLICATE = 2;
  public static final int REJECTED_DISABLED = 3;

  public static final String[] names = { "ACCEPTED", "REJECTED_UNNAMED", "REJECTED_DUPLICATE", "REJECTED_DISABLED", };

  public static String name(int e) { return names[e]; }
}

