// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InboundBatteryNotification extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static InboundBatteryNotification getRootAsInboundBatteryNotification(ByteBuffer _bb) { return getRootAsInboundBatteryNotification(_bb, new InboundBatteryNotification()); }
  public static InboundBatteryNotification getRootAsInboundBatteryNotification(ByteBuffer _bb, InboundBatteryNotification obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public InboundBatteryNotification __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int trackerId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public float batteryLevel() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean charging() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createInboundBatteryNotification(FlatBufferBuilder builder,
      int trackerId,
      float batteryLevel,
      boolean charging) {
    builder.startTable(3);
    InboundBatteryNotification.addBatteryLevel(builder, batteryLevel);
    InboundBatteryNotification.addTrackerId(builder, trackerId);
    InboundBatteryNotification.addCharging(builder, charging);
    return InboundBatteryNotification.endInboundBatteryNotification(builder);
  }

  public static void startInboundBatteryNotification(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addTrackerId(FlatBufferBuilder builder, int trackerId) { builder.addShort(0, (short) trackerId, (short) 0); }
  public static void addBatteryLevel(FlatBufferBuilder builder, float batteryLevel) { builder.addFloat(1, batteryLevel, 0.0f); }
  public static void addCharging(FlatBufferBuilder builder, boolean charging) { builder.addBoolean(2, charging, false); }
  public static int endInboundBatteryNotification(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public InboundBatteryNotification get(int j) { return get(new InboundBatteryNotification(), j); }
    public InboundBatteryNotification get(InboundBatteryNotification obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public InboundBatteryNotificationT unpack() {
    InboundBatteryNotificationT _o = new InboundBatteryNotificationT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(InboundBatteryNotificationT _o) {
    int _oTrackerId = trackerId();
    _o.setTrackerId(_oTrackerId);
    float _oBatteryLevel = batteryLevel();
    _o.setBatteryLevel(_oBatteryLevel);
    boolean _oCharging = charging();
    _o.setCharging(_oCharging);
  }
  public static int pack(FlatBufferBuilder builder, InboundBatteryNotificationT _o) {
    if (_o == null) return 0;
    return createInboundBatteryNotification(
      builder,
      _o.getTrackerId(),
      _o.getBatteryLevel(),
      _o.getCharging());
  }
}

