// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class OutboundTrackerStatusNotificationT {
  private int trackerId;
  private int status;
  private float batteryLevel;
  private boolean charging;

  public int getTrackerId() { return trackerId; }

  public void setTrackerId(int trackerId) { this.trackerId = trackerId; }

  public int getStatus() { return status; }

  public void setStatus(int status) { this.status = status; }

  public float getBatteryLevel() { return batteryLevel; }

  public void setBatteryLevel(float batteryLevel) { this.batteryLevel = batteryLevel; }

  public boolean getCharging() { return charging; }

  public void setCharging(boolean charging) { this.charging = charging; }


  public OutboundTrackerStatusNotificationT() {
    this.trackerId = 0;
    this.status = 0;
    this.batteryLevel = 0.0f;
    this.charging = false;
  }
}

