// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.driver_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * Request to initiate driver communication with the server.
 */
@SuppressWarnings("unused")
public final class RegisterDriver extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static RegisterDriver getRootAsRegisterDriver(ByteBuffer _bb) { return getRootAsRegisterDriver(_bb, new RegisterDriver()); }
  public static RegisterDriver getRootAsRegisterDriver(ByteBuffer _bb, RegisterDriver obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RegisterDriver __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * A short string identifying your driver. This may be used in a UI to display connected drivers, and as a
   * configuration key for per-driver settings.
   */
  public String driverName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer driverNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer driverNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  /**
   * Controls which fields are serialised in SkeletonUpdate messages. If this is null, SkeletonUpdate messages will
   * not be sent.
   */
  public solarxr_protocol.datatypes.BoneMask boneMask() { return boneMask(new solarxr_protocol.datatypes.BoneMask()); }
  public solarxr_protocol.datatypes.BoneMask boneMask(solarxr_protocol.datatypes.BoneMask obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createRegisterDriver(FlatBufferBuilder builder,
      int driverNameOffset,
      int boneMaskOffset) {
    builder.startTable(2);
    RegisterDriver.addBoneMask(builder, boneMaskOffset);
    RegisterDriver.addDriverName(builder, driverNameOffset);
    return RegisterDriver.endRegisterDriver(builder);
  }

  public static void startRegisterDriver(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDriverName(FlatBufferBuilder builder, int driverNameOffset) { builder.addOffset(0, driverNameOffset, 0); }
  public static void addBoneMask(FlatBufferBuilder builder, int boneMaskOffset) { builder.addOffset(1, boneMaskOffset, 0); }
  public static int endRegisterDriver(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // driver_name
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RegisterDriver get(int j) { return get(new RegisterDriver(), j); }
    public RegisterDriver get(RegisterDriver obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public RegisterDriverT unpack() {
    RegisterDriverT _o = new RegisterDriverT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(RegisterDriverT _o) {
    String _oDriverName = driverName();
    _o.setDriverName(_oDriverName);
    if (boneMask() != null) _o.setBoneMask(boneMask().unpack());
    else _o.setBoneMask(null);
  }
  public static int pack(FlatBufferBuilder builder, RegisterDriverT _o) {
    if (_o == null) return 0;
    int _driverName = _o.getDriverName() == null ? 0 : builder.createString(_o.getDriverName());
    int _boneMask = _o.getBoneMask() == null ? 0 : solarxr_protocol.datatypes.BoneMask.pack(builder, _o.getBoneMask());
    return createRegisterDriver(
      builder,
      _driverName,
      _boneMask);
  }
}

