// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.device;

@SuppressWarnings("unused")
public final class DeviceBoundMessage {
  private DeviceBoundMessage() { }
  public static final byte NONE = 0;
  public static final byte solarxr_protocol_device_commands_LetMeInRequest = 1;
  public static final byte solarxr_protocol_device_data_feed_DataFeedResponse = 2;
  public static final byte solarxr_protocol_device_commands_TapResponse = 3;
  public static final byte solarxr_protocol_device_commands_SetWifiResponse = 4;

  public static final String[] names = { "NONE", "solarxr_protocol_device_commands_LetMeInRequest", "solarxr_protocol_device_data_feed_DataFeedResponse", "solarxr_protocol_device_commands_TapResponse", "solarxr_protocol_device_commands_SetWifiResponse", };

  public static String name(int e) { return names[e]; }
}

