// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.datatypes

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * To be used inside unions
 */
@Suppress("unused")
class DeviceIdTable : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceIdTable {
        __init(_i, _bb)
        return this
    }
    val id : solarxr_protocol.datatypes.DeviceId? get() = id(solarxr_protocol.datatypes.DeviceId())
    fun id(obj: solarxr_protocol.datatypes.DeviceId) : solarxr_protocol.datatypes.DeviceId? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsDeviceIdTable(_bb: ByteBuffer): DeviceIdTable = getRootAsDeviceIdTable(_bb, DeviceIdTable())
        @JvmStatic
        fun getRootAsDeviceIdTable(_bb: ByteBuffer, obj: DeviceIdTable): DeviceIdTable {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun startDeviceIdTable(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        @JvmStatic
        fun endDeviceIdTable(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
