// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.application.data_feed;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * All of the data components related to a single data feed. A data feed is comprised
 * of device data, and tracker data.
 *
 * A data feed might send data only when it changes/updates, and we should make no
 * assumptions that the data is actually delivered. If you want to guarantee
 * delivery and avoid dropped observations of data (such as a user-initiated
 * button press), it is better to use the RPC system.
 */
@SuppressWarnings("unused")
public final class DataFeedUpdate extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static DataFeedUpdate getRootAsDataFeedUpdate(ByteBuffer _bb) { return getRootAsDataFeedUpdate(_bb, new DataFeedUpdate()); }
  public static DataFeedUpdate getRootAsDataFeedUpdate(ByteBuffer _bb, DataFeedUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DataFeedUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.application.data_feed.device_data.DeviceData devices(int j) { return devices(new solarxr_protocol.application.data_feed.device_data.DeviceData(), j); }
  public solarxr_protocol.application.data_feed.device_data.DeviceData devices(solarxr_protocol.application.data_feed.device_data.DeviceData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int devicesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public solarxr_protocol.application.data_feed.device_data.DeviceData.Vector devicesVector() { return devicesVector(new solarxr_protocol.application.data_feed.device_data.DeviceData.Vector()); }
  public solarxr_protocol.application.data_feed.device_data.DeviceData.Vector devicesVector(solarxr_protocol.application.data_feed.device_data.DeviceData.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public solarxr_protocol.application.data_feed.tracker.TrackerData syntheticTrackers(int j) { return syntheticTrackers(new solarxr_protocol.application.data_feed.tracker.TrackerData(), j); }
  public solarxr_protocol.application.data_feed.tracker.TrackerData syntheticTrackers(solarxr_protocol.application.data_feed.tracker.TrackerData obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int syntheticTrackersLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public solarxr_protocol.application.data_feed.tracker.TrackerData.Vector syntheticTrackersVector() { return syntheticTrackersVector(new solarxr_protocol.application.data_feed.tracker.TrackerData.Vector()); }
  public solarxr_protocol.application.data_feed.tracker.TrackerData.Vector syntheticTrackersVector(solarxr_protocol.application.data_feed.tracker.TrackerData.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  /**
   * This must represent a set, where there is no more than one bone for a `BodyPart`.
   */
  public solarxr_protocol.application.data_feed.Bone bones(int j) { return bones(new solarxr_protocol.application.data_feed.Bone(), j); }
  public solarxr_protocol.application.data_feed.Bone bones(solarxr_protocol.application.data_feed.Bone obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int bonesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public solarxr_protocol.application.data_feed.Bone.Vector bonesVector() { return bonesVector(new solarxr_protocol.application.data_feed.Bone.Vector()); }
  public solarxr_protocol.application.data_feed.Bone.Vector bonesVector(solarxr_protocol.application.data_feed.Bone.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createDataFeedUpdate(FlatBufferBuilder builder,
      int devicesOffset,
      int syntheticTrackersOffset,
      int bonesOffset) {
    builder.startTable(3);
    DataFeedUpdate.addBones(builder, bonesOffset);
    DataFeedUpdate.addSyntheticTrackers(builder, syntheticTrackersOffset);
    DataFeedUpdate.addDevices(builder, devicesOffset);
    return DataFeedUpdate.endDataFeedUpdate(builder);
  }

  public static void startDataFeedUpdate(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addDevices(FlatBufferBuilder builder, int devicesOffset) { builder.addOffset(0, devicesOffset, 0); }
  public static int createDevicesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDevicesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSyntheticTrackers(FlatBufferBuilder builder, int syntheticTrackersOffset) { builder.addOffset(1, syntheticTrackersOffset, 0); }
  public static int createSyntheticTrackersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSyntheticTrackersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addBones(FlatBufferBuilder builder, int bonesOffset) { builder.addOffset(2, bonesOffset, 0); }
  public static int createBonesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBonesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endDataFeedUpdate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DataFeedUpdate get(int j) { return get(new DataFeedUpdate(), j); }
    public DataFeedUpdate get(DataFeedUpdate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public DataFeedUpdateT unpack() {
    DataFeedUpdateT _o = new DataFeedUpdateT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(DataFeedUpdateT _o) {
    solarxr_protocol.application.data_feed.device_data.DeviceDataT[] _oDevices = new solarxr_protocol.application.data_feed.device_data.DeviceDataT[devicesLength()];
    for (int _j = 0; _j < devicesLength(); ++_j) {_oDevices[_j] = (devices(_j) != null ? devices(_j).unpack() : null);}
    _o.setDevices(_oDevices);
    solarxr_protocol.application.data_feed.tracker.TrackerDataT[] _oSyntheticTrackers = new solarxr_protocol.application.data_feed.tracker.TrackerDataT[syntheticTrackersLength()];
    for (int _j = 0; _j < syntheticTrackersLength(); ++_j) {_oSyntheticTrackers[_j] = (syntheticTrackers(_j) != null ? syntheticTrackers(_j).unpack() : null);}
    _o.setSyntheticTrackers(_oSyntheticTrackers);
    solarxr_protocol.application.data_feed.BoneT[] _oBones = new solarxr_protocol.application.data_feed.BoneT[bonesLength()];
    for (int _j = 0; _j < bonesLength(); ++_j) {_oBones[_j] = (bones(_j) != null ? bones(_j).unpack() : null);}
    _o.setBones(_oBones);
  }
  public static int pack(FlatBufferBuilder builder, DataFeedUpdateT _o) {
    if (_o == null) return 0;
    int _devices = 0;
    if (_o.getDevices() != null) {
      int[] __devices = new int[_o.getDevices().length];
      int _j = 0;
      for (solarxr_protocol.application.data_feed.device_data.DeviceDataT _e : _o.getDevices()) { __devices[_j] = solarxr_protocol.application.data_feed.device_data.DeviceData.pack(builder, _e); _j++;}
      _devices = createDevicesVector(builder, __devices);
    }
    int _syntheticTrackers = 0;
    if (_o.getSyntheticTrackers() != null) {
      int[] __syntheticTrackers = new int[_o.getSyntheticTrackers().length];
      int _j = 0;
      for (solarxr_protocol.application.data_feed.tracker.TrackerDataT _e : _o.getSyntheticTrackers()) { __syntheticTrackers[_j] = solarxr_protocol.application.data_feed.tracker.TrackerData.pack(builder, _e); _j++;}
      _syntheticTrackers = createSyntheticTrackersVector(builder, __syntheticTrackers);
    }
    int _bones = 0;
    if (_o.getBones() != null) {
      int[] __bones = new int[_o.getBones().length];
      int _j = 0;
      for (solarxr_protocol.application.data_feed.BoneT _e : _o.getBones()) { __bones[_j] = solarxr_protocol.application.data_feed.Bone.pack(builder, _e); _j++;}
      _bones = createBonesVector(builder, __bones);
    }
    return createDataFeedUpdate(
      builder,
      _devices,
      _syntheticTrackers,
      _bones);
  }
}

