// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.application.data_feed;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class StartDataFeedT {
  private solarxr_protocol.application.data_feed.DataFeedConfigT[] dataFeeds;

  public solarxr_protocol.application.data_feed.DataFeedConfigT[] getDataFeeds() { return dataFeeds; }

  public void setDataFeeds(solarxr_protocol.application.data_feed.DataFeedConfigT[] dataFeeds) { this.dataFeeds = dataFeeds; }


  public StartDataFeedT() {
    this.dataFeeds = null;
  }
}

