// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class TapDetectionSetupResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TapDetectionSetupResponse {
        __init(_i, _bb)
        return this
    }
    val trackerId : solarxr_protocol.datatypes.TrackerId? get() = trackerId(solarxr_protocol.datatypes.TrackerId())
    fun trackerId(obj: solarxr_protocol.datatypes.TrackerId) : solarxr_protocol.datatypes.TrackerId? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        fun getRootAsTapDetectionSetupResponse(_bb: ByteBuffer): TapDetectionSetupResponse = getRootAsTapDetectionSetupResponse(_bb, TapDetectionSetupResponse())
        fun getRootAsTapDetectionSetupResponse(_bb: ByteBuffer, obj: TapDetectionSetupResponse): TapDetectionSetupResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTapDetectionSetupResponse(builder: FlatBufferBuilder, trackerIdOffset: Int) : Int {
            builder.startTable(1)
            addTrackerId(builder, trackerIdOffset)
            return endTapDetectionSetupResponse(builder)
        }
        fun startTapDetectionSetupResponse(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addTrackerId(builder: FlatBufferBuilder, trackerId: Int) = builder.addOffset(0, trackerId, 0)
        fun endTapDetectionSetupResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
