// automatically generated by the FlatBuffers compiler, do not modify

package slimevr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ResetRequestT {
  private boolean quick;

  public boolean getQuick() { return quick; }

  public void setQuick(boolean quick) { this.quick = quick; }


  public ResetRequestT() {
    this.quick = false;
  }
}

