// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Cancels the current recording, aborting the process and discarding the data
 */
@Suppress("unused")
class AutoBoneCancelRecordingRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AutoBoneCancelRecordingRequest {
        __init(_i, _bb)
        return this
    }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsAutoBoneCancelRecordingRequest(_bb: ByteBuffer): AutoBoneCancelRecordingRequest = getRootAsAutoBoneCancelRecordingRequest(_bb, AutoBoneCancelRecordingRequest())
        @JvmStatic
        fun getRootAsAutoBoneCancelRecordingRequest(_bb: ByteBuffer, obj: AutoBoneCancelRecordingRequest): AutoBoneCancelRecordingRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun startAutoBoneCancelRecordingRequest(builder: FlatBufferBuilder) = builder.startTable(0)
        @JvmStatic
        fun endAutoBoneCancelRecordingRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
