// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

@Suppress("unused")
class Path private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val FilePath: UByte = 1u
        const val FolderPath: UByte = 2u
        val names : Array<String> = arrayOf("NONE", "FilePath", "FolderPath")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
