// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * Response of the SaveFileNotification after the user interacts with the file save request
 */
@Suppress("unused")
class SaveFileRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SaveFileRequest {
        __init(_i, _bb)
        return this
    }
    /**
     * ID of the SaveFile, given by SaveFileNotification
     */
    val id : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    /**
     * Where to save the file, if null, server will choose where to save it
     */
    val path : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val pathAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun pathInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    /**
     * Iff false, the file save will be canceled
     */
    val canceled : Boolean?
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else null
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsSaveFileRequest(_bb: ByteBuffer): SaveFileRequest = getRootAsSaveFileRequest(_bb, SaveFileRequest())
        @JvmStatic
        fun getRootAsSaveFileRequest(_bb: ByteBuffer, obj: SaveFileRequest): SaveFileRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createSaveFileRequest(builder: FlatBufferBuilder, id: UInt, pathOffset: Int, canceled: Boolean?) : Int {
            builder.startTable(3)
            addPath(builder, pathOffset)
            addId(builder, id)
            canceled?.run { addCanceled(builder, canceled) }
            return endSaveFileRequest(builder)
        }
        @JvmStatic
        fun startSaveFileRequest(builder: FlatBufferBuilder) = builder.startTable(3)
        @JvmStatic
        fun addId(builder: FlatBufferBuilder, id: UInt) = builder.addInt(0, id.toInt(), 0)
        @JvmStatic
        fun addPath(builder: FlatBufferBuilder, path: Int) = builder.addOffset(1, path, 0)
        @JvmStatic
        fun addCanceled(builder: FlatBufferBuilder, canceled: Boolean) = builder.addBoolean(2, canceled, false)
        @JvmStatic
        fun endSaveFileRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
