// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class SetPauseTracking : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SetPauseTracking {
        __init(_i, _bb)
        return this
    }
    val pauseTracking : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsSetPauseTracking(_bb: ByteBuffer): SetPauseTracking = getRootAsSetPauseTracking(_bb, SetPauseTracking())
        @JvmStatic
        fun getRootAsSetPauseTracking(_bb: ByteBuffer, obj: SetPauseTracking): SetPauseTracking {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createSetPauseTracking(builder: FlatBufferBuilder, pauseTracking: Boolean) : Int {
            builder.startTable(1)
            addPauseTracking(builder, pauseTracking)
            return endSetPauseTracking(builder)
        }
        @JvmStatic
        fun startSetPauseTracking(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addPauseTracking(builder: FlatBufferBuilder, pauseTracking: Boolean) = builder.addBoolean(0, pauseTracking, false)
        @JvmStatic
        fun endSetPauseTracking(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
