// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * When the server detects a public network profile
 */
@Suppress("unused")
class StatusPublicNetwork : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StatusPublicNetwork {
        __init(_i, _bb)
        return this
    }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsStatusPublicNetwork(_bb: ByteBuffer): StatusPublicNetwork = getRootAsStatusPublicNetwork(_bb, StatusPublicNetwork())
        @JvmStatic
        fun getRootAsStatusPublicNetwork(_bb: ByteBuffer, obj: StatusPublicNetwork): StatusPublicNetwork {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun startStatusPublicNetwork(builder: FlatBufferBuilder) = builder.startTable(0)
        @JvmStatic
        fun endStatusPublicNetwork(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
