// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class VRCConfigRecommendedValues : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VRCConfigRecommendedValues {
        __init(_i, _bb)
        return this
    }
    val legacyMode : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val shoulderTrackingDisabled : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val userHeight : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val calibrationRange : Float
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val calibrationVisuals : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val trackerModel : UByte
        get() {
            val o = __offset(14)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun spineMode(j: Int) : UByte {
        val o = __offset(16)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val spineModeLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    val spineModeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun spineModeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val avatarMeasurementType : UByte
        get() {
            val o = __offset(18)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val shoulderWidthCompensation : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsVRCConfigRecommendedValues(_bb: ByteBuffer): VRCConfigRecommendedValues = getRootAsVRCConfigRecommendedValues(_bb, VRCConfigRecommendedValues())
        @JvmStatic
        fun getRootAsVRCConfigRecommendedValues(_bb: ByteBuffer, obj: VRCConfigRecommendedValues): VRCConfigRecommendedValues {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createVRCConfigRecommendedValues(builder: FlatBufferBuilder, legacyMode: Boolean, shoulderTrackingDisabled: Boolean, userHeight: Float, calibrationRange: Float, calibrationVisuals: Boolean, trackerModel: UByte, spineModeOffset: Int, avatarMeasurementType: UByte, shoulderWidthCompensation: Boolean) : Int {
            builder.startTable(9)
            addSpineMode(builder, spineModeOffset)
            addCalibrationRange(builder, calibrationRange)
            addUserHeight(builder, userHeight)
            addShoulderWidthCompensation(builder, shoulderWidthCompensation)
            addAvatarMeasurementType(builder, avatarMeasurementType)
            addTrackerModel(builder, trackerModel)
            addCalibrationVisuals(builder, calibrationVisuals)
            addShoulderTrackingDisabled(builder, shoulderTrackingDisabled)
            addLegacyMode(builder, legacyMode)
            return endVRCConfigRecommendedValues(builder)
        }
        @JvmStatic
        fun startVRCConfigRecommendedValues(builder: FlatBufferBuilder) = builder.startTable(9)
        @JvmStatic
        fun addLegacyMode(builder: FlatBufferBuilder, legacyMode: Boolean) = builder.addBoolean(0, legacyMode, false)
        @JvmStatic
        fun addShoulderTrackingDisabled(builder: FlatBufferBuilder, shoulderTrackingDisabled: Boolean) = builder.addBoolean(1, shoulderTrackingDisabled, false)
        @JvmStatic
        fun addUserHeight(builder: FlatBufferBuilder, userHeight: Float) = builder.addFloat(2, userHeight, 0.0)
        @JvmStatic
        fun addCalibrationRange(builder: FlatBufferBuilder, calibrationRange: Float) = builder.addFloat(3, calibrationRange, 0.0)
        @JvmStatic
        fun addCalibrationVisuals(builder: FlatBufferBuilder, calibrationVisuals: Boolean) = builder.addBoolean(4, calibrationVisuals, false)
        @JvmStatic
        fun addTrackerModel(builder: FlatBufferBuilder, trackerModel: UByte) = builder.addByte(5, trackerModel.toByte(), 0)
        @JvmStatic
        fun addSpineMode(builder: FlatBufferBuilder, spineMode: Int) = builder.addOffset(6, spineMode, 0)
        @JvmStatic
        fun createSpineModeVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        @JvmStatic
        fun startSpineModeVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        @JvmStatic
        fun addAvatarMeasurementType(builder: FlatBufferBuilder, avatarMeasurementType: UByte) = builder.addByte(7, avatarMeasurementType.toByte(), 0)
        @JvmStatic
        fun addShoulderWidthCompensation(builder: FlatBufferBuilder, shoulderWidthCompensation: Boolean) = builder.addBoolean(8, shoulderWidthCompensation, false)
        @JvmStatic
        fun endVRCConfigRecommendedValues(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
