namespace solarxr_protocol.data_feed.server;

enum ResetAvailability: uint8 {
    AVAILABLE,
    NEEDS_FULL_RESET,
    NEEDS_POSITIONAL_HEAD,
    NO_TRACKERS,
}

/// Contains various of flags / guards that inform the GUI
/// about possible actions or blocked states.
/// The idea is to have one source of truth for all these rules
/// that are spread accross the GUI.
table ServerGuards {
    yaw_reset: ResetAvailability;
    mounting_reset: ResetAvailability;
    can_do_user_height_calibration: bool;
}
