namespace solarxr_protocol.rpc.settings;

/// Settings for the skeletal model that are toggles.
table ModelToggles {
    force_arms_from_hmd: bool = null;
    floor_clip: bool = null;
    skating_correction: bool = null;
    toe_snap: bool = null;
    foot_plant: bool = null;
    self_localization: bool = null;
    use_position: bool = null;
    enforce_constraints: bool = null;
    correct_constraints: bool = null;
}

// Settings for leg tweaks
table LegTweaksSettings {
    correction_strength: float32 = null;
}

table SkeletonHeight {
    hmd_height: float32 = null;
    floor_height: float32 = null;
}

/// Settings for the skeletal model.
table ModelSettings {
    toggles: ModelToggles;
    ratios: ModelRatios;
    leg_tweaks: LegTweaksSettings;
    skeleton_height: SkeletonHeight;
}
