// automatically generated by the FlatBuffers compiler, do not modify

package slimevr_protocol.data_feed;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class DataFeedMessageHeaderT {
  private slimevr_protocol.data_feed.DataFeedMessageUnion message;

  public slimevr_protocol.data_feed.DataFeedMessageUnion getMessage() { return message; }

  public void setMessage(slimevr_protocol.data_feed.DataFeedMessageUnion message) { this.message = message; }


  public DataFeedMessageHeaderT() {
    this.message = null;
  }
}

