// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc.settings;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ModelTogglesT {
  private Boolean extendedSpine;
  private Boolean extendedPelvis;
  private Boolean extendedKnee;
  private Boolean forceArmsFromHmd;
  private Boolean floorClip;
  private Boolean skatingCorrection;
  private Boolean viveEmulation;
  private Boolean toeSnap;
  private Boolean footPlant;

  public Boolean getExtendedSpine() { return extendedSpine; }

  public void setExtendedSpine(Boolean extendedSpine) { this.extendedSpine = extendedSpine; }

  public Boolean getExtendedPelvis() { return extendedPelvis; }

  public void setExtendedPelvis(Boolean extendedPelvis) { this.extendedPelvis = extendedPelvis; }

  public Boolean getExtendedKnee() { return extendedKnee; }

  public void setExtendedKnee(Boolean extendedKnee) { this.extendedKnee = extendedKnee; }

  public Boolean getForceArmsFromHmd() { return forceArmsFromHmd; }

  public void setForceArmsFromHmd(Boolean forceArmsFromHmd) { this.forceArmsFromHmd = forceArmsFromHmd; }

  public Boolean getFloorClip() { return floorClip; }

  public void setFloorClip(Boolean floorClip) { this.floorClip = floorClip; }

  public Boolean getSkatingCorrection() { return skatingCorrection; }

  public void setSkatingCorrection(Boolean skatingCorrection) { this.skatingCorrection = skatingCorrection; }

  public Boolean getViveEmulation() { return viveEmulation; }

  public void setViveEmulation(Boolean viveEmulation) { this.viveEmulation = viveEmulation; }

  public Boolean getToeSnap() { return toeSnap; }

  public void setToeSnap(Boolean toeSnap) { this.toeSnap = toeSnap; }

  public Boolean getFootPlant() { return footPlant; }

  public void setFootPlant(Boolean footPlant) { this.footPlant = footPlant; }


  public ModelTogglesT() {
    this.extendedSpine = null;
    this.extendedPelvis = null;
    this.extendedKnee = null;
    this.forceArmsFromHmd = null;
    this.floorClip = null;
    this.skatingCorrection = null;
    this.viveEmulation = null;
    this.toeSnap = null;
    this.footPlant = null;
  }
}

