// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc.settings;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ModelRatiosT {
  private Float imputeSpineFromTopDown;
  private Float imputeSpineCurvature;
  private Float interpHipLegs;
  private Float interpKneeTrackerAnkle;
  private Float interpKneeAnkle;

  public Float getImputeSpineFromTopDown() { return imputeSpineFromTopDown; }

  public void setImputeSpineFromTopDown(Float imputeSpineFromTopDown) { this.imputeSpineFromTopDown = imputeSpineFromTopDown; }

  public Float getImputeSpineCurvature() { return imputeSpineCurvature; }

  public void setImputeSpineCurvature(Float imputeSpineCurvature) { this.imputeSpineCurvature = imputeSpineCurvature; }

  public Float getInterpHipLegs() { return interpHipLegs; }

  public void setInterpHipLegs(Float interpHipLegs) { this.interpHipLegs = interpHipLegs; }

  public Float getInterpKneeTrackerAnkle() { return interpKneeTrackerAnkle; }

  public void setInterpKneeTrackerAnkle(Float interpKneeTrackerAnkle) { this.interpKneeTrackerAnkle = interpKneeTrackerAnkle; }

  public Float getInterpKneeAnkle() { return interpKneeAnkle; }

  public void setInterpKneeAnkle(Float interpKneeAnkle) { this.interpKneeAnkle = interpKneeAnkle; }


  public ModelRatiosT() {
    this.imputeSpineFromTopDown = null;
    this.imputeSpineCurvature = null;
    this.interpHipLegs = null;
    this.interpKneeTrackerAnkle = null;
    this.interpKneeAnkle = null;
  }
}

