// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc.settings;

/**
 * Tracker groups for velocity configuration.
 * Roles with trackers on two sides (like ANKLES, FEET) correspond to both left and right trackers.
 * NECK and SHOULDERS are excluded due to being mostly static and too close to HMD.
 */
@SuppressWarnings("unused")
public final class VelocityRoleGroup {
  private VelocityRoleGroup() { }
  public static final int FEET = 0;
  public static final int ANKLES = 1;
  public static final int KNEES = 2;
  public static final int CHEST = 3;
  public static final int WAIST = 4;
  public static final int ELBOWS = 5;

  public static final String[] names = { "FEET", "ANKLES", "KNEES", "CHEST", "WAIST", "ELBOWS", };

  public static String name(int e) { return names[e]; }
}

