namespace solarxr_protocol.rpc;

enum ResetType: uint8 {
    /// Resets the yaw (horizontal) axis
    Yaw,
    /// Resets all axes
    Full,
    /// Second pose for calibrating mounting rotation
    Mounting,
}

enum ResetStatus: uint8 {
    Started,
    Finished,
}

table ResetRequest {
    reset_type: ResetType;
    /// Which body parts to reset. Server handles it if empty (usually all)
    body_parts: [solarxr_protocol.datatypes.BodyPart];
    delay: float = null;
}

table ResetResponse {
    reset_type: ResetType;
    status: ResetStatus;
    /// Should return the body parts reset / being reset
    body_parts: [solarxr_protocol.datatypes.BodyPart];
    /// gives the time in seconds passed since the start of the reset
    /// Starts at 0. Should be equal to 'duration' when status == FINISHED
    progress: int;
    duration: int;
}

/// Clears mounting reset data, defaulting to the manually set mounting orientations
table ClearMountingResetRequest {}

enum ArmsMountingResetMode: uint8 {
    /// Upper arm going back and forearm going forward
    BACK,
    /// Arms going forward
    FORWARD,
    /// Arms going up to the sides into a t-pose
    T_POSE_UP,
    /// Arms going down to the sides from a t-pose
    T_POSE_DOWN
}

// Resets settings request and response
table ResetsSettingsRequest {}
table ResetsSettingsResponse {
    /// Makes it so feet will be mounting reset when passing no BodyPart
    reset_mounting_feet: bool;
    arms_mounting_reset_mode: ArmsMountingResetMode;
    yaw_reset_smooth_time: float32;
    save_mounting_reset: bool;
    reset_hmd_pitch: bool;
}
table ChangeResetsSettingsRequest {
    /// Makes it so feet will be mounting reset when passing no BodyPart
    reset_mounting_feet: bool;
    arms_mounting_reset_mode: ArmsMountingResetMode;
    yaw_reset_smooth_time: float32;
    save_mounting_reset: bool;
    reset_hmd_pitch: bool;
}
