namespace solarxr_protocol.rpc;

enum SkeletonBone: uint8 {
    NONE = 0,
    HEAD = 1,
    NECK = 2,
    UPPER_CHEST = 3,
    CHEST = 4,
    WAIST = 5,
    HIP = 6,
    HIPS_WIDTH = 7,
    UPPER_LEG = 8,
    LOWER_LEG = 9,
    FOOT_LENGTH = 10,
    FOOT_SHIFT = 11,
    SHOULDERS_DISTANCE = 12,
    SHOULDERS_WIDTH = 13,
    UPPER_ARM = 14,
    LOWER_ARM = 15,
    HAND_Y = 16,
    HAND_Z = 17,
}

table SkeletonPart {
    bone: SkeletonBone;
    value: float;
}

table SkeletonProportionsRequest {}
table SkeletonProportionsResponse {
    skeleton_parts: [SkeletonPart];
    skeleton_height: float;
}
table ChangeSkeletonProportionsRequest {
    bone: SkeletonBone;
    value: float;
}

table SkeletonProportionsResetAllRequest {}

/// Makes a temporary change to legtweaks. This is not saved to disk, and can be
/// cleared with `LegTweaksTmpClear`
table LegTweaksTmpChange {
    floor_clip: bool = null;
    skating_correction: bool = null;
    toe_snap: bool = null;
    foot_plant: bool = null;
}

/// Clears the legtweaks temporary state back to what the config has.
/// Setting a field to `true` will reset that field.
table LegTweaksTmpClear {
    floor_clip: bool = false;
    skating_correction: bool = false;
    toe_snap: bool = false;
    foot_plant: bool = false;
}

table SetPauseTrackingRequest {
    /// Pauses skeleton tracking if true, resumes skeleton tracking if false.
    pause_tracking: bool;
}

/// Requests the current state of tracking pause
table TrackingPauseStateRequest {}
table TrackingPauseStateResponse {
    /// Skeleton tracking is paused if true, skeleton tracking is unpaused if false.
    tracking_paused: bool;
}

/// Toggles for the skeletal model.
table SkeletonToggles {
    force_arms_from_hmd: bool = null;
    floor_clip: bool = null;
    skating_correction: bool = null;
    toe_snap: bool = null;
    foot_plant: bool = null;
    mocap_mode: bool = null;
    use_tracker_positions: bool = null;
    enforce_constraints: bool = null;
    correct_constraints: bool = null;
}

/// Ratios for the skeletal model. Accepted values for them range from 0 to 1
table SkeletonRatios {
    /// Compute missing spine bones as a ratio of the next available upper and lower bones.
    impute_spine_from_upper_to_lower: float32 = null;
    /// Computes the curvature between 2 adjacent missing spine bones. Higher = more curvature.
    impute_spine_curvature: float32 = null;
    /// How much to average the hip's yaw and roll with the upper legs'.
    interpolate_hip_with_upper_legs: float32 = null;
    /// How much to average the upper legs' yaw and roll with the lower legs'.
    interpolate_upper_legs_with_lower_legs: float32 = null;
    /// Strength of skating correction. Enabled via SkeletonToggles.skating_correction
    skating_correction_strength: float32 = null;
}

enum FilteringType: uint8 {
	NONE = 0,
	SMOOTHING = 1,
	PREDICTION = 2
}

/// Filtering (e.g smoothing) applied to the skeleton's movements
table SkeletonFiltering {
    type: FilteringType;
    /// A higher value results in more filtering (0 to 1).
    amount: float32;
}

// Skeleton settings request and response
table SkeletonSettingsRequest {}
table SkeletonSettingsResponse {
    toggles: SkeletonToggles;
    ratios: SkeletonRatios;
    filtering: SkeletonFiltering;
}
table ChangeSkeletonSettingsRequest {
    toggles: SkeletonToggles;
    ratios: SkeletonRatios;
    filtering: SkeletonFiltering;
}

// User height request and response (used to compute the user's height)
table UserHeightRequest {}
table UserHeightResponse {
    hmd_height: float32 = null;
    floor_height: float32 = null;
}
table ChangeUserHeightRequest {
    hmd_height: float32 = null;
    floor_height: float32 = null;
}
