namespace solarxr_protocol.rpc;

table EnableStayAlignedRequest {
    enable: bool;
}

enum StayAlignedRelaxedPose: uint8 {
    STANDING = 0,
    SITTING = 1,
    FLAT = 2
}

table DetectStayAlignedRelaxedPoseRequest {
    pose: StayAlignedRelaxedPose;
}

table ResetStayAlignedRelaxedPoseRequest {
    pose: StayAlignedRelaxedPose;
}

table StayAlignedSettingsRequest {}
table StayAlignedSettingsResponse {
    enabled: bool;
    standing_enabled: bool;
    standing_upper_leg_angle: float32;
    standing_lower_leg_angle: float32;
    standing_foot_angle: float32;
    sitting_enabled: bool;
    sitting_upper_leg_angle: float32;
    sitting_lower_leg_angle: float32;
    sitting_foot_angle: float32;
    flat_enabled: bool;
    flat_upper_leg_angle: float32;
    flat_lower_leg_angle: float32;
    flat_foot_angle: float32;
}
table ChangeStayAlignedSettingsRequest {
    enabled: bool;
    standing_enabled: bool;
    standing_upper_leg_angle: float32;
    standing_lower_leg_angle: float32;
    standing_foot_angle: float32;
    sitting_enabled: bool;
    sitting_upper_leg_angle: float32;
    sitting_lower_leg_angle: float32;
    sitting_foot_angle: float32;
    flat_enabled: bool;
    flat_upper_leg_angle: float32;
    flat_lower_leg_angle: float32;
    flat_foot_angle: float32;
}

table CompleteStayAlignedResponse {}

table StayAlignedHideCorrectionRequest {
    hide_correction: bool;
}
