include "../datatypes/datatypes.fbs";

namespace solarxr_protocol.rpc;

table AssignTrackerRequest {
    tracker_id: uint16;
    body_position: solarxr_protocol.datatypes.BodyPart;
    mounting_orientation: solarxr_protocol.datatypes.math.Quat;
    display_name: string;
}

// Tap Detection settings request and response
table TapDetectionSettingsRequest {}
table TapDetectionSettingsResponse {
    full_reset_delay: float = null;
    full_reset_enabled: bool = null;
    full_reset_taps: uint8 = null;
    yaw_reset_delay: float = null;
    yaw_reset_enabled: bool = null;
    yaw_reset_taps: uint8 = null;
    mounting_reset_delay: float = null;
    mounting_reset_enabled: bool = null;
    mounting_reset_taps: uint8 = null;
    number_trackers_over_threshold: uint8 = null;
    yaw_reset_tracker: solarxr_protocol.datatypes.BodyPart = null;
    full_reset_tracker: solarxr_protocol.datatypes.BodyPart = null;
    mounting_reset_tracker: solarxr_protocol.datatypes.BodyPart = null;
}
table ChangeTapDetectionSettingsRequest {
    full_reset_delay: float = null;
    full_reset_enabled: bool = null;
    full_reset_taps: uint8 = null;
    yaw_reset_delay: float = null;
    yaw_reset_enabled: bool = null;
    yaw_reset_taps: uint8 = null;
    mounting_reset_delay: float = null;
    mounting_reset_enabled: bool = null;
    mounting_reset_taps: uint8 = null;
    number_trackers_over_threshold: uint8 = null;
    yaw_reset_tracker: solarxr_protocol.datatypes.BodyPart = null;
    full_reset_tracker: solarxr_protocol.datatypes.BodyPart = null;
    mounting_reset_tracker: solarxr_protocol.datatypes.BodyPart = null;
}

/// Sets the TapDetection setup mode.
table TapDetectionSetupModeRequest {
    /// When true, TapDetection triggering a tracker will assign it instead of doing a reset.
    setup_mode: bool = null;
}

/// Indicates which tracker got triggered by TapDetection while setup mode is enabled
table TapDetectionSetupNotification {
    tracker_id: uint16;
}

/// If no tracker ID is given, it's the setting for every tracker/device
table MagToggleRequest {
    tracker_id: uint16;
}

/// If no tracker ID is given, it's the setting for every tracker/device
table MagToggleResponse {
    tracker_id: uint16;
    enable: bool;
}

/// If no tracker ID is given, it's the setting for every tracker/device
table ChangeMagToggleRequest {
    tracker_id: uint16;
    enable: bool;
}
