namespace solarxr_protocol.rpc;

enum VRCTrackerModel: uint8 {
    UNKNOWN = 0,
    SPHERE = 1,
    SYSTEM = 2,
    BOX = 3,
    AXIS = 4,
}

enum VRCSpineMode: uint8 {
    UNKNOWN = 0,
    LOCK_HIP = 1,
    LOCK_HEAD = 2,
    LOCK_BOTH = 3,
}

enum VRCAvatarMeasurementType: uint8 {
    UNKNOWN = 0,
    HEIGHT = 1,
    ARM_SPAN = 2
}

table VRCConfigValidity {
    legacy_mode_ok: bool;
    shoulder_tracking_ok: bool;
    user_height_ok: bool;
    calibration_range_ok: bool;
    calibration_visuals_ok: bool;
    tracker_model_ok: bool;
    spine_mode_ok: bool;
    avatar_measurement_type_ok: bool;
    shoulder_width_compensation_ok: bool;
}

table VRCConfigValues {
    legacy_mode: bool;
    shoulder_tracking_disabled: bool;
    user_height: float;
    calibration_range: float;
    calibration_visuals: bool;
    tracker_model: VRCTrackerModel;
    spine_mode: VRCSpineMode;
    avatar_measurement_type: VRCAvatarMeasurementType;
    shoulder_width_compensation: bool;
}

table VRCConfigRecommendedValues {
    legacy_mode: bool;
    shoulder_tracking_disabled: bool;
    user_height: float;
    calibration_range: float;
    calibration_visuals: bool;
    tracker_model: VRCTrackerModel;
    spine_mode: [VRCSpineMode];
    avatar_measurement_type: VRCAvatarMeasurementType;
    shoulder_width_compensation: bool;
}

table VRCConfigStateRequest {}

/// Sent every time the vrchat config state gets updated
/// used to display vrchat missconfig settings to the user
table VRCConfigStateChangeResponse {
    is_supported: bool;
    validity: VRCConfigValidity;
    state: VRCConfigValues;
    recommended: VRCConfigRecommendedValues;
     /// Just a list of keys from the VRCConfigValidity table.
     // Didnt want to make it a full table, because it would be another pain to maintain. Strings are fine for that.
     // copium
    muted: [string];
}

// Mute or unmute a vrc setting warning from its key
table VRCConfigSettingToggleMute {
    /// Key from VRCConfigValidity
    key: string;
}