// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { KeyValues, KeyValuesT } from '../../../solarxr-protocol/application/pub-sub/key-values';
import { Payload, unionToPayload, unionListToPayload } from '../../../solarxr-protocol/application/pub-sub/payload';
import { Topic, unionToTopic, unionListToTopic } from '../../../solarxr-protocol/application/pub-sub/topic';
import { TopicHandle, TopicHandleT } from '../../../solarxr-protocol/application/pub-sub/topic-handle';
import { TopicId, TopicIdT } from '../../../solarxr-protocol/application/pub-sub/topic-id';
import { Bytes, BytesT } from '../../../solarxr-protocol/datatypes/bytes';
import { StringTable, StringTableT } from '../../../solarxr-protocol/datatypes/string-table';


/**
 * Data that is sent from publishers to subscribers
 */
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

topicType():Topic {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Topic.NONE;
}

topic<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

payloadType():Payload {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Payload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startMessage(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTopicType(builder:flatbuffers.Builder, topicType:Topic) {
  builder.addFieldInt8(0, topicType, Topic.NONE);
}

static addTopic(builder:flatbuffers.Builder, topicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, topicOffset, 0);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:Payload) {
  builder.addFieldInt8(2, payloadType, Payload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, payloadOffset, 0);
}

static endMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMessage(builder:flatbuffers.Builder, topicType:Topic, topicOffset:flatbuffers.Offset, payloadType:Payload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.startMessage(builder);
  Message.addTopicType(builder, topicType);
  Message.addTopic(builder, topicOffset);
  Message.addPayloadType(builder, payloadType);
  Message.addPayload(builder, payloadOffset);
  return Message.endMessage(builder);
}

unpack(): MessageT {
  return new MessageT(
    this.topicType(),
    (() => {
      let temp = unionToTopic(this.topicType(), this.topic.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })(),
    this.payloadType(),
    (() => {
      let temp = unionToPayload(this.payloadType(), this.payload.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: MessageT): void {
  _o.topicType = this.topicType();
  _o.topic = (() => {
      let temp = unionToTopic(this.topicType(), this.topic.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
  _o.payloadType = this.payloadType();
  _o.payload = (() => {
      let temp = unionToPayload(this.payloadType(), this.payload.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class MessageT {
constructor(
  public topicType: Topic = Topic.NONE,
  public topic: TopicHandleT|TopicIdT|null = null,
  public payloadType: Payload = Payload.NONE,
  public payload: BytesT|KeyValuesT|StringTableT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const topic = builder.createObjectOffset(this.topic);
  const payload = builder.createObjectOffset(this.payload);

  return Message.createMessage(builder,
    this.topicType,
    topic,
    this.payloadType,
    payload
  );
}
}
